### ISSUE TITLE
Clarification about the understanding of the some problems in the assignment?

### ISSUE THREAD

**Issue by RashedHUBC** [STAT540-UBC/Discussion#117]
Hello,
I have some confusion in answering some questions. Can you help me in better understanding?
1. Question 1.1: what does it mean by light cleaning? Does it mean to work with factor levels? 
2.  Question 3.2: "What is the (estimated) false discovery rate of this “hits” list? How many of these hits do we expect to be false discoveries?" Should we interpret the results based on the best hit (with minimum q value)? 
3. In Question 5 I am confused to treat the model. As we have to use two covariates and need to find out DE probes where treatment is significant so shouldn't we use the additive model here? Because considering interaction we can't interpret the treatment alone. As in 5.2 we need to test the interaction I think the model in 5.1 and 5.2 are different (first one without interaction and the second one with interaction). Am I right? Or for whole 5 we just need one model!!! Please clarify.
4. Question 6.3: It is unclear that which data file we need to save. There are 3 possibilities: 1) before mapping probes to genes (seems not wanted) 2) after mapping to genes (whole list) 3) after mapping to genes (only the DE). I am confused in choosing between 2 and 3. In Question 7 we need to plot both of the DE and non DE genes. This makes me confused. Also the wanted interpretation on FDR makes confused with the results wanted in Question 3.2. 

Sorry to bother. Actually I need some understanding. Thanks for your help @santina and @marjanfarahbod .

**Comment by marjanfarahbod** [comment]
Hi, I'm glad that you put it down here. 

1. No. It means basically checking the data, refers to lectures 3 and 4. It is expected that you load the data and consider some usual things to check, mostly counts and numbers, the rest of the Q1 are the mandatory specific things to look at. 
2. I think no clarification is needed here. The question in the assignment is quite clear. 
3. It is asking for the same model, as defined in the title of the question "full model"
4. You are basically doing pre-processing and cleaning in this step. Like in any other experiment, you want to save the results from your pre-processing for down stream analysis. 

In the case of FDR, I should refer you to lecture 11. Please notice that one of the goals for this assignment is that you apply the course materials in biological experiments, guided by the seminars. Since this is a graduate level course, it is expected that you do your own research for better understanding of some topics or their applications.

**Comment by hui-tony-zk** [comment]
Here's what I found on FDR interpretation:

```
● Example:
○ m = 10000
● p-values:
○ cutoff at .01 assumes that you likely found about
100 false positives
○ cutoff of .0001 assumes that you only found 1
false positive, but at what cost?
● q-values:
○ set q-value cutoff at .05, and be sure that only 5%
of the significant genes found are likely to be false
positives
```

Slide 28 of http://cbcb.umd.edu/~hcorrada/CFG/lectures/student_presentations/qvalue.pdf

In the case of question 3.2, I think the estimated FDR would be the highest FDR in your list (aka, the q-value). For example, in your list of 50 hits, the highest q value is 0.01, which means 1% of your 50 hits are false discoveries = 0.5 hits are false discoveries = none are false discoveries. I think that's the right interpretation - please correct me if I'm wrong.

**Comment by RashedHUBC** [comment]
Thanks @marjanfarahbod for the clarification. @hui-tony-zk I will check the results. Thanks for the comments.
