### ISSUE TITLE
Any insight on fitting a regression line? Q5.3

### ISSUE THREAD

**Issue by David-Rattray** [STAT540-UBC/Discussion#118]
Hey, I've been trying to play around with geom_smooth() and stat_smooth() in ggplot to add the regression lines to the four panels, but all the code options I type produce to error messages, but also make no changes to the plot I have.
I currently make the plot with 

```
ggplot(combine, aes(x = combine$time, y = combine$Expression, colour = Treatment)) 
+ ggtitle("Probe Comparison") 
+ labs(x = "Timepoint", y = "Expression") 
+ geom_point() + facet_wrap(~Probe)
```

Which yields the next image...
![rplot](https://cloud.githubusercontent.com/assets/16545002/13833417/eb6dd70e-eba2-11e5-8cb8-97e64c3ce023.png)
 As you can see no lines yet. I've added things to the code like:  
- stat_smooth(se = F) 
- geom_smooth 
- geom_smooth(method='lm',formula=combine$Expression~combine$time)
- geom_smooth(aes(x = combine$time, y = combine$Expression, colour = Treatment), method=lm, se=FALSE) + facet_wrap(~Probe, scales = "free_x")

With no success. Really have no clue what is going on at this point. Any nudges in the right direction?

Thanks for your help @santina and @marjanfarahbod .

**Comment by santina** [comment]
1. In your first line within `aes()`, it should just be 
`aes(x = time, y = cExpression, colour = Treatment)` because you already specify which from dataframe these columns are supposed to be looked at in your first argument to ggplot.

2. The numbers shouldn't be equally spaced (there's a bigger difference between 4 and 24 than other intervals right?) Either you didn't make sure the numbers are numeric type when you did Q1.2 or it's cuz the previous point about `aes()`.

3.  You're on the right track with geom_smooth. See [this](http://stackoverflow.com/questions/15633714/adding-a-regression-line-on-a-ggplot)

**Comment by hui-tony-zk** [comment]
Try this

```
ggplot(combine, aes(x =time, y =Expression, colour = Treatment)) + 
  ggtitle("Probe Comparison") + 
  labs(x = "Timepoint", y = "Expression") + 
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~Probe)
```
