### ISSUE TITLE
Group project: initial information 2017

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#132]
Hi, it's time to form and declare your team! Your team should have 4 - 5 people. 

Click on "edit" on this post and copy everything below the horizontal line, paste it into your comment, and fill out the information. Just one comment per team.

------------------------

| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| example: Santina Lin | Bioinformatics  | Machine learning and data mining  |  @santina |
|  |   |  |
|  |   |  |
|  |   |  |
|  |   |  |

Team name: 

One paragraph on the basic idea of the project:

**Comment by dakep** [comment]
hi @santina, only the user that created a post can edit it iirc, so we can't copy & paste "everything below the horizontal line".

Please correct me if I'm wrong though!

**Comment by santina** [comment]
Oh no... Thanks for letting me know!  Here then I'll copy paste the raw markdown for the table. You can just copy & paste from here. 

```

| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| example: Santina Lin | Bioinformatics  | Machine learning and data mining  |  @santina |
|  |   |  |
|  |   |  |
|  |   |  |
|  |   |  |

Team name: 

One paragraph on the basic idea of the project: 


```

**Comment by wvictor14** [comment]
Hi Santina, could you clarify how many members should each group be composed of? You mentioned in your comment 4-5, but on the assignments page it says 4-6[https://stat540-ubc.github.io/subpages/assignments.html](url)

**Comment by Hbrewis** [comment]
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Samantha Schaffner | Medical Genetics  | Neuroepigenetics of human development and Parkinson's Disease  |  @samschaf |
| Cassia Warren | Interdisciplinary Oncology   | Biomarker development for treatments of Pancreatic cancer | @cwarren5124|
| Hilary Brewis  | Medical Genetics  | Histone variants and chromatin structure | @hbrewis |
| Randip Gill  | Educational Psychology  | Social epigenetics | @rg7486 |
| Lisa Wei | Bioinformatics  | Cancer genomics, sequence analysis | @suminwei2772 |

**Team name:** Methylhomies

**One paragraph on the basic idea of the project:** 

DNA methylation (DNAm), or covalent attachment of a methyl group to the 5’ position of cytosine bases located in CpG dinucleotides, plays a crucial role in maintaining patterns of gene expression during human development and aging. Along with other epigenetic modifications, DNAm is sensitive to environmental influences and can change over an individual’s lifespan. Thus, understanding the human methylome is important for determining both biomarkers for - and direct pathways implicating - health and disease [1]. Aberrant DNAm patterns have been correlated with common neurodegenerative disorders, including Alzheimer’s Disease and Parkinson’s Disease [2], as well as with mental disorders such as schizophrenia [3,4]. However, much of the literature on either the diseased or healthy brain methylome fails to separate DNAm data by cell type composition - a major driver of DNAm variability - or by brain region [5, 6]. We aim to provide a baseline of variation in the normal human methylome across various brain regions and according to proportions of neurons versus glia. We will use a publicly available dataset of n=122 healthy individuals aged 40-105 [7], consisting of reads obtained using the Illumina HumanMethylation450 BeadChip array platform. We will process the reads and quantify methylation levels, determine the proportions of neurons in the prefrontal cortex, entorhinal cortex, superior temporal gyrus and the cerebellum with a cell type prediction algorithm, and correlate the neuronal proportion with the amount of methylation in these regions [8]. This analysis will inform on (1) the difference in methylation levels between cortex and cerebellum and within cortical subregions and (2) the relationship within neuronal proportion and methylation levels in all regions analyzed. Our findings will be validated using an independent dataset: the Allen Brain Atlas’ Human Developing Brain cohort of n=16 healthy individuals aged 4 months - 37 years (http://brain-map.org/). Ultimately, the project will shed light on the importance of variability in methylation between brain regions, providing a guideline to analyze existing brain epigenetic literature and to plan robust experimental design moving forward.

**References:**

[1] Bernstein, B. E. _et al_. (2007). The Mammalian Epigenome. Cell. 128(4): 669-681. 

[2] Sanchez-Mut, J. V., _et al._ (2016). Human DNA methylomes of neurodegenerative diseases show common epigenomic patterns. Transl Pysch. 6: e817.

[3] Huang, H. S., & Akbarian, S. (2007). GAD1 mRNA expression and DNA methylation in prefrontal cortex of subjects with schizophrenia. PloS one, 2(8), e809.

[4] Huang, H. S., _et al_. (2007). Prefrontal dysfunction in schizophrenia involves mixed-lineage leukemia 1-regulated histone methylation at GABAergic gene promoters. Journal of Neuroscience, 27(42), 11254-11262.

[5] Shin, J., _et al_. (2014). Decoding neural transcriptomes and epigenomes via high-throughput sequencing. Nat Neurosci 17(11): 1463-1475.

[6] Jaffe, A. E. & Irizarry, R. A. (2014). Accounting for cellular heterogeneity is critical in epigenome-wide association studies. Genome Biology. 15: R31.

[7] Hannon, E. _et al_. (2015). Interindividual methylomic variation across blood, cortex, and cerebellum: implications for epigenetic studies of neurological and neuropsychiatric phenotypes. Epigenetics. 10(11): 1024-1032.

[8] Morris, T. J., & Beck, S. (2015). Analysis pipelines and packages for Infinium HumanMethylation450 BeadChip (450k) data. Methods. 72: 3-8.

**Comment by Jwong684** [comment]
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Jasper Wong | Genome Science and Technology | Cancer genetics and epigenetics  |  @jwong684 |
| Grant de Jong | Genome Science and Technology  | Structural genomics, Population genomics | @dejonggr |
| Stephen Lee | Genome Science and Technology  | Cancer genomics, Epigenomics | @slee94 |
| Mary He  |  Statistics | Biostatistics and machine learning  | @MaryHe |
| Jie Cui | Statistics | Biostatistics and machine learning | @jie-cui |

**Team name:** 5-mC's on an island

**Gene Expression and DNA Methylation Analysis of IDH1/2 and TET Mutated Patients in Acute Myeloid Leukemia and Lower Grade Glioma**

Project summary: Neomorphic IDH mutations are prevalently observed specifically in Acute Myeloid Leukemia (AML) and Lower Grade Glioma (LGG) and impart an aberrant function for the encoded enzyme, resulting in production of the oncometabolite 2-hydroxyglutarate (2-HG). 2-HG inhibits the Tet-mediated DNA demethylation process, resulting in widespread regulatory changes in the cell. In LGG for instance, it has been shown that hypermethylation of specific regions of the genome inhibits an insulator protein called CTCF from binding DNA, resulting in overexpression of particular oncogenes. We are interested in comparing the global gene expression and DNA methylation landscapes between LGG and AML to assess whether IDH mutations result in similar cellular consequences in these two distinct cancer types. Inactivating TET2 mutations are observed to be mutually exclusive to IDH1/2 mutations in AML; we are also interested in investigating whether these mutations recapitulate the consequences of IDH mutations. To do this, we will use datasets provided by The Cancer Genome Atlas (TCGA), an endeavour that sequenced entire genomes of cancer patients for open access use.

**Comment by santina** [comment]
Hi @wvictor14 Sorry for getting back to you super late ... 

I hope that didn't affect your group formation decision too much. Sorry for having conflicting information on the website. 

We would like to keep it at fIve. Four is okay. If you form a group of 6, we would expect that your project scope is bigger to ensure equal amount of work among all members. 

@ppavlidis  @farnushfarhadi

**Comment by fangwuwang** [comment]
| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Annie Cavalla | Bioinformatics  | Cancer genomics, single cell transcriptomics  |  @acavalla |
| Rawnak Hoque  | Genome Science and Technology  | Genome scale data analysis | 	@rawnakhoque  
| Somdeb Paul | Genome Science and Technology  | Transcriptomics | @psomdeb25
| Fangwu Wang  | Medical Genetics  | Stem cell biology, Epigenomics | @fangwuwang

Team name: Bloodies

Project summary: Our project is interested in how hematopoietic stem cells, a rare stem cell population able to regenerate all erythroid, myeloid and lymphoid lineages in humans, make cell fate decisions during multiple-stage differentiation. We will obtain RNA-seq, DNA Methylome and ChIP-seq data from a European public resource (BLUEPRINT: http://dcc.blueprint-epigenome.eu/#/home). We will study the transcription factors (TFs) specifically expressed in one cell type (transcriptional signature) and the epigenomic features of different cells.

The preliminary plan includes:
1) Using RNA-seq data to find signature genes and generate a list of essential TFs for the development of each cell type; 
2) Using methylome and ChIP-seq of histone marks to identify active/poised promoter and enhancer regions, and recognize the TF binding motif within these regions to infer the important transcriptional regulation during differentiation; 
3) Correlating these promoter/enhancer regions from (2) with gene expression to verify the transcriptional regulation; 
4) Constructing a TF network for lineage differentiation using these datasets and known TF interactions from literature.
There will be comparisons and statistical analyses involved in each step.

**Comment by dvalgardson** [comment]
Name | Program | Lab | Interest/Expertise | GitHub ID
-----|---------|-----|--------------------|----------
Sonja | Neuroscience | Wellington | Alzheimer's Disease, inflammation, lipids | @sonjasoo
Dani | Zoology | Jankowski| Neotropical birds, ectoparasites, ecology | @dvalgardson
Dalia  | Bioinformatics | Hsiao | Clinical Genomics, Variant calling | @Dalalghamdi
Nolan  | Botany | Lee | Genomics, biophysics | @nolanshe

Team name: Chlamy

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The unicellular green alga *Chlamydomonas reinhardtii* is a facultative autotroph with a haploid-dominant life cycle, dividing mitotically under normal growth conditions. In response to nitrogen starvation, vegetative cells differentiate into gametes of one of two mating types. *MT+* gametes carry the *MT+* locus on chromosome 6, while *MT-* gametes carry the *MT-* locus on chromosome 6. Transcription of sex-specific genes leads to sexual differentiation and fusion of the *MT+* and *MT- gametes*, forming a binucleate zygote. Then, a cascade of zygote-specific genes are expressed, many of which self-assemble as a zygote-specific cell wall, giving resistance to both desiccation and freezing. When normal growth conditions are restored, the dormant zygote initiates meiosis and the four recombinant haploid products resume vegetative growth.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Chlamydomonas reinhardtii* has had its transcriptome sequenced across a wide array of environmental conditions and strains in both the mitotic and gametic stages of its life cycle. However, the zygote transcriptome has yet to be fully characterized due its durable cell wall, which is very difficult to penetrate. Our project will involve a comparison of transcription levels in the mitotic, gametic and zygotic stages of its life cycle, under the normal conditions that facilitate these three stages. This will enable the confirmation of sex-specific genes and the identification of zygote-specific genes, the latter of which will be examined in greater detail. RNA-seq of two zygotes has been completed, as well as genome sequencing of the four haploid strains giving rise to them, enabling the allelic composition of the zygote transcriptome to be determined. In this way, genes expressed within the zygote that display allele-specific expression can be identified, including those specific to a particular strain or sex. The latter phenomenon, termed genomic imprinting, has been observed in a large number of plants and animals, including humans, but has yet to be found in unicellular organisms. Its discovery in *Chlamydomonas reinhardtii* would have important implications for the evolution of this phenomenon in higher eukaryotes.

**Comment by kevinjep** [comment]
| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Kenny Askelson | Zoology, MSc | Wildlife Biology | @kaskelso |
| Stephanie Blain | Zoology, MSc | Evolutionary ecology | @stephblain |
| Yann Dubois | CPSC | Machine learning & data science | @YannDubs |
| Kevin Jepson | Genome Science & Technology, MSc | Single-cell sequencing | @kevinjep |
| Mackenzie Kinney | Zoology, PhD | Molecular biology, evolutionary ecology | @mhkinney |
| Garrett McCarthy | UBCO Biology, MSc | Yeast Population Genetics | @mccag94 |

Team name: The Zoo Crew

As prostate cancer metastasizes throughout the body the 5-year survival rate drops from 100% to approximately 28% according to the American Cancer Society. A major issue with diagnosing and treating advanced prostate cancer is that performing metastatic biopsies is often infeasible due to the invasive nature of such procedures. In order to monitor metastatic prostate cancer in real-time, oncologists have begun looking at circulating tumor cells as a potential alternative. Our team’s STAT540 project will analyze single-cell miRNA sequencing data from the circulating tumor cells of late-stage prostate cancer patients, and make comparisons with data from early-stage patients and primary prostate tumors. The goal of this analysis is to determine if there are any useful miRNA-related biomarkers in circulating tumor cells which could be of use to clinicians when diagnosing and treating late-stage prostate cancer patients.

**Comment by gjahesh** [comment]
| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Ashley Arnold | Microbiology and Immunology | Metagenomics | @acarnold | 
| Amreen Toor  | Experimental Medicine | Cellular and Molecular Biology  |  @atoor92 |
| Kaitlyn Harper | Public Health | Intestinal Health, Gut Microbiome | @oktokat |
| Vivian Lac  | Interdisciplinary Oncology |  Pathology and Cancer Genetics | @vivianlac |
| Golnaz Jahesh| Bioinformatics | _denovo_ Sequence Assembly | @gjahesh |


Team name: MetaForests

__Evaluating Long Term Productivity of the Forest Soil with Metagenomic and Metatranscriptomic Analysis__

Project Summary : Our group project will involve analyzing metagenomic (DNA-seq) and metatranscriptomic (RNA-seq) data generated from a forest soil environment. Samples were collected near O’Connor Lake in Kamloops, British Columbia, a site that is part of the Long-Term Soil Productivity (LTSP) study where an overall objective was to evaluate the long term effects of forest harvesting, specifically organic matter removal and soil compaction, on soil biological activity and productivity. We will analyze data from surface samples collected from a reference i.e a natural site where no forest harvesting took place and one treated site where a moderate level of forest harvesting and organic layer removal occurred. As the LTSP study seeks to understand the long-term effects of forest harvesting, samples were collected at different seasons to generate a time series. For our project we will look at samples collected from September 2013 and February 2014.

With this dataset we hope to identify metabolic pathways related to organic carbon degradation that differ between the reference and harvested treatment. By having both DNA and RNA sequence data we hope to identify differences in the metabolic potential (DNA) and metabolic expression (RNA) of key degradation pathways and determine whether season has any effect. 

| Treatment | DNA Samples | RNA samples |
| ------------- | ------------- | ------------- | 
|Reference (Natural site)| N=6 ( n=3 for September, n = 3 for February) | N=6 ( n=3 for September, n = 3 for February) |
| Moderate harvesting | N=6 ( n=3 for September, n = 3 for February) | N=6 ( n=3 for September, n = 3 for February) |

**Comment by dakep** [comment]
### Team AutoInflam
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
|Kristen Gibson | Medical Genetics | Genetics and Immunology  |@kgibso29|
|Miguel Ramirez | Genome Science and Technology | Genomics/Epigenomics |@cmramirez91|
|David Kepplinger | Statistics | Robust Statistics, High Dimensional Problems, Computational Statistics | @dakep |
|Adrian Jones | Statistics |Spatial Statistics and Environmental Statistics | @AdrianLJones |
|Kristy Dever | Medical Genetics |Transcription Regulation  | @kdever|
|Allen Manser | Genome Science and Technology |Genomics & Technology  | @AM-GH |

#### Project Summary
The Pediatric Rheumatology Team at BC Children’s Hospital (BCCH) has been caring for a child, currently 11 years old, that has been sick with fevers, rashes, enlarged liver and spleen, and poor growth since 1 year of age. Based on clinical considerations it is clear that this child has an autoinflammatory disease yet the symptoms and genetic testing do not fit with any known autoinflammatory disease. Without greater understanding of this child’s disease, the prognosis is lifelong poor health, disability and chronic inflammatory sequelae. The child has an older and a younger sibling. The older sibling is well. The younger sibling was otherwise healthy until a few months ago when signs of autoinflammatory disease appeared. The parents come from a small community with a limited gene pool and likely have ancient consanguinity. 

#### Primary Objectives
1. Identify variants of interest using clinical exome sequencing of the patient and parents
1. Identify a list of relevant differentially expressed genes comparing the patient to the parents and siblings (as well as publicly available repositories)
1. Identify differences in inflammatory protein concentrations in blood between the patient and family members, and in the CSF between the patient and unrelated controls

#### Other Potential Questions of Interest 
1. Correlate findings to clinical data

#### Available Data for Analysis
1. Whole exome sequencing (research and clinical grade) of DNA extracted from blood from the patient and parents.
1. Whole blood RNA sequencing from the affected child (on two separate occasions), parents (once) and siblings (once).
1. Concentrations of 40 inflammatory proteins in blood sera obtained from the child on 4-5 occasions over ~2yrs, parents (1x), siblings (1x), and 3 non-related children that underwent tonsillectomy at BCCH (1x).
1. Concentrations of 40 inflammatory proteins in cerebrospinal fluid (CSF) obtained from the child and from 3 non-related children with a primary disease that does not have central nervous system (CNS) involvement.
1. Clinical grade phenotyping of circulating immune cells that drive adaptive (not innate) immunity. The phenotyping provides information about the abundance and activation state of these cells.
1. Clinical information including therapies and laboratory measures of inflammation.

**Comment by wvictor14** [comment]
| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Victor Yuan | Genome Science and Technology | Placental Epigenetics |@wvictor14 |
| Michael Yuen| Medical Genetics| Cancer Genomics| @myuen89 |
| Nivretta Thatra| Bioinformatics| Neuroscience| @nivretta|
| Ming Wan | Statistics| statistical genetics and machine | @MingWan10|
| Anni Zhang| Genome Science and Technology| Pancreatic Cancer/Cancer metabolism | @annizubc |

Team name: Methyl Badassays

DNA methylation (DNAm) - the covalent modification of DNA at CpG sites resulting in attached methyl groups - regulates gene expression. A large portion of DNAm variability is associated with genetic ancestry** and is heritable [1]. These marks vary across cell types, temporal development, and can change due to environmental stimuli. These factors are all taken into account when researchers are trying to use gene expression analysis when studying diseases. Differentially methylated CpG sites associated with pathology can be confounded by CpGs associated with genetic ancestry causing spurious results. Therefore, genetic ancestry, as a covariate, needs to be accounted for in any epigenome-wide association study (EWAS). An unpublished set of placental samples (33 Caucasians; 12 Asians) will be used to identify a set of top-ranked CpG sites that associate with self-reported ethnicity. By identifying the CpG sites which are specifically associated with Asian and Caucasian ethnicities in placenta tissues, we propose to reduce false positive CpG site discoveries when looking for associations with placental pathologies [2] by accounting for genetic ancestry -associated CpGs in a published dataset lacking reliable ethnicity information. 

**Note: It is important to distinguish between genetic ancestry, race and ethnicity. The latter two are social constructs and have no genetic definition. In contrast, genetic ancestry is a continuum which describes the architecture of genome variation between populations [3].

1. Fraser HB, Lam LL, Neumann SM, Kobor MS. Population-specificity of human DNA methylation. Genome Biol. 2012;13(2):R8.
2. Sparks PJ. Do biological, sociodemographic, and behavioral characteristics explain racial/ethnic disparities in preterm births? Soc Sci Med. 2009;68(9):1667-1675.
3. Yudell M, Roberts D, DeSalle R, Tishkoff S. SCIENCE AND SOCIETY. taking race out of human genetics. Science. 2016;351(6273):564-565.

**Comment by abaghela** [comment]
| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| example: Santina Lin | Bioinformatics  | Machine learning and data mining  |  @santina |
|  |   |  |
|  |   |  |
|  |   |  |
|  |   |  |

Team name: 

One paragraph on the basic idea of the project:

**Comment by abaghela** [comment]
| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Arjun Baghela | Bioinformatics  | Immunology & Transcriptomics  |  @abaghela |
| Emma Graham | Bioinformatics  | Machine Learning & Metabolomics | @emmagraham
| Allison Tai | Bioinformatics  | Machine Learning & DNA Structure | @faelicy
| Eric Chu | Bioinformatics   | Neuroscience & Transcriptomics  | @echu113

Team name: Undecided

One paragraph on the basic idea of the project:

Asthma is characterized by chronic inflammation, and affects over 400 million children and adults worldwide (1).  The heterogeneity of the disease manifests as variation in clinical onset, responsiveness to treatment and comorbidities (2). Upstream events in the lung epithelial cells of the lower airway have been postulated to initiate Type II inflammation, which is mediated by CD4+ T cells, leading to cytokine production and remodeling of the cellular environment in the lower airway. Recent studies using RNA-seq data have characterized the Type II immune response in CD4+ T cells; however, the upstream events in epithelial cells that initiate this response remain unknown (3,4).  A study recently published, which obtained RNA-Seq and methylation profiles for 76 asthma patients, investigated the genetic and epigenetic markers upregulated in lower airway epithelial cells during asthmatic responses (5). However, the conclusions of the study are limited by numerous confounding factors such as medication usage, comorbidities and artefacts of experimentation, which can obscure the detection of meaningful biological signals.  Furthermore, the generation of interactive networks with WGCNA (6) in the aforementioned study may have removed meaningful connections in an attempt to reduce noise, and also has difficulties incorporating heterogeneous data. RNAseq and methylation data from lung epithelial cells in subjects with and without asthma will be analyzed to determine master regulator genes that initiate the Type II inflammatory response in lung epithelial cells. To begin our analysis, RNAseq data will be processed to remove the effect of confounding variables, and used to construct a co-expression network. Similarly, we will construct a co-expression network with differentially methylated CpGs (DMCs). Both these networks may give us insights into the genetic and epigenetic signatures that influence variation in asthma endotypes. We may try other analyses too, if we have time. These include determining whether methylation levels at DMCs are correlated with expression levels of nearby genes and integrating DMC and RNA-Seq data using a network-interaction based approach. 

References 
1. Pawankar R.  2014. Allergic diseases and asthma: a global public health concern and a call to action. World Allergy Organ. J. 7: 12.
2. Wesolowska-Andersen A, Seibold MA. Airway molecular endotypes of asthma: dissecting the heterogeneity. Curr Opin Allergy Clin Immunol. 2015;15(2):163–168. doi: 
3. Locksley RM. Asthma and allergic inflammation. Cell. 2010;140:777–783.
4. Seumois, Grégory, et al. "Transcriptional profiling of Th2 cells identifies pathogenic features associated with asthma." The Journal of Immunology 197.2 (2016): 655-664
5. Nicodemus-Johnson, Jessie et al. “DNA Methylation in Lung Cells Is Associated with Asthma Endotypes and Genetic Risk.” JCI Insight 1.20 (2016): e90151. PMC. Web. 26 Jan. 2017.
6. Langfelder P, Horvath S. WGCNA: an R package for weighted correlation network analysis. BMC Bioinformatics. 2008;9:559. doi:10.1186/1471-2105-9-559.

**Comment by HAMacKay** [comment]
# Group information: 

| Name | Department/Program | Experties/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Christina Michalski | Experimental Medicine (PhD) | Immunology | @ChristinaMi |
| Heather A. MacKay | Wood Science (MSc) | Plant Biotechnology and molecular biology |  @HAMacKay |
| Jeffery Tang | Nondegree | Genomics and  molecular biology  | @jt1013 |
| Nichalle Brito |  Biochemistry and molecular biology (MSc) | Proteomics and viral proteases | @Nichalle |
| Rebecca Asiimwe | Bioinformatics (MSc) | Cancer Research | @rasiimwe |


Team Name: FBC LENSE

# Project information:

Our group aim:
1. Identify mutation variants and compare differences between CEMT_7 (breast fibrocystic disease) cell line to the normal cell lines (CEMT_8 and CEMT_9).
2. Assess correlation between the identified mutated sequences to the changes in gene expression between healthy and breast fibrocystic cells.
3. Identify differentially methylated promoter regions.
4. Assess correlation between these promoter regions to the RNA-seq gene expression levels.
5. Perform downstream analysis to identify gene function.

Our dataset consists of three cell lines:
 
1. CEMT_7 =  MCF10A, Mammary gland-Breast with pathology Mammary gland-Breast Fibrocystic Disease 
2. CEMT_8 =  184-hTert-L9, Mammary gland-Breast, Normal (earlier passage)
3. CEMT_9 =  184-hTert-L2, Mammary gland-Breast, Normal (later passage)
 
And for each of the above cell lines we have:
 
- illumina_bisulfite  (methylation data)
- illumina_exoncapture  (exon data)
- illumina_wgss (whole genome sequencing)
- illumina_chip     (chip-seq data)
- illumina_mirn   (miRNA-seq)
- illumina_wtss  (RNA-seq data)


For gene expression analysis we will be comparing one of the normal samples against the diseased cell line sample to find and draw a correlation between which genes are expressed in diseased cells than in the normal tissue. We will also analyze how DNA mutations impact methylation and transcription factor binding capacity and how these changes affect gene expression levels.
