### ISSUE TITLE
Assignment questions 2 and 3

### ISSUE THREAD

**Issue by suminwei2772** [STAT540-UBC/Discussion#139]
@farnushfarhadi @santina @singha53 @ppavlidis 
For assginment Question 2,
When you say "make a quantitative statement about presence of an outlier: e.g., quantify for each sample, whether it “sticks out” compared to the other samples," can we do, for instance, a fold change of that sample's expression value compared to the mean of the rest of the samples? What other sort of quantification would you suggest?

For Question 3:
#3.1
Below is my code to generate the model (eBayes-corrected):

DesignMat <- model.matrix(~ Treatment, meta_dat)
datfit <- lmFit(dat, DesignMat)
datEBFit <- eBayes(datfit)
topTable(datEBFit)

I get the following as output:
                 logFC   AveExpr         t      P.Value    adj.P.Val        B
200779_at   -0.7613410 13.983184 -8.577428 1.419183e-08 0.0001750755 9.623149
202912_at   -1.7199499 12.764302 -8.161121 3.365296e-08 0.0001750755 8.840436
214696_at   -1.9074941 11.730937 -8.155234 3.407195e-08 0.0001750755 8.829176
223394_at   -1.2644771 10.909886 -8.147206 3.465212e-08 0.0001750755 8.813808
223774_at   -1.1696606  9.529931 -8.080341 3.989741e-08 0.0001750755 8.685431
209020_at   -1.0223766 10.677979 -7.939997 5.373691e-08 0.0001750755 8.413709
202672_s_at -3.5302487  9.716310 -7.904577 5.795528e-08 0.0001750755 8.344646
220468_at   -2.4132680  6.488711 -7.876047 6.160022e-08 0.0001750755 8.288875
223982_s_at -0.9256205 10.907060 -7.729633 8.438527e-08 0.0001933190 8.000666
226924_at   -0.6366539  9.588851 -7.726141 8.502396e-08 0.0001933190 7.993752

I originally had "~0+Treatment" for the design matrix (which makes more sense to me) in order to get the means of each condition but when I did that, I got very small adjusted and unadjusted p-values, on the order of 10e-50 (see below), so that can't be correct. I'm not sure where the error is though.

Treatmentcigarette_smoke Treatmentcontrol  AveExpr        F      P.Value    adj.P.Val
200817_x_at                 15.67340         15.65254 15.66252 281000.8 1.418767e-50 7.114505e-47
212391_x_at                 15.74824         15.72935 15.73838 275343.9 1.786920e-50 7.114505e-47
212284_x_at                 15.65463         15.64879 15.65159 273262.2 1.947581e-50 7.114505e-47
217733_s_at                 15.91063         15.90590 15.90816 269508.8 2.278429e-50 7.114505e-47
212185_x_at                 15.68315         15.71314 15.69879 269343.6 2.294329e-50 7.114505e-47
212790_x_at                 15.70471         15.68590 15.69489 264816.3 2.780818e-50 7.114505e-47
212661_x_at                 15.71348         15.69230 15.70243 264257.3 2.848280e-50 7.114505e-47
211978_x_at                 15.66126         15.65500 15.65800 261812.4 3.165031e-50 7.114505e-47
200717_x_at                 15.67461         15.65782 15.66585 260670.5 3.325933e-50 7.114505e-47
213084_x_at                 15.81458         15.75279 15.78234 260074.2 3.413471e-50 7.114505e-47

#3.2 
I did the following to try to get the number of genes that satisfy each threshold:

length(p.adjust(datEBFit$F.p.value, method = "fdr") < 0.05)
length(p.adjust(datEBFit$F.p.value, method = "none") < 0.001)

But for both lines of code, I got all the genes back (22737 of them), which again can't be right.  
I would appreciate any hints/suggestions as to what might be going wrong...
Thank you!

**Comment by rbalshaw** [comment]
Hint: consider what the model ~ 0 + Treatment means in terms of parameters, and then think about what hypothesis are being tested to generate those p-values.  Then, what hypotheses are being tested if you use a model like ~ Treatment.

**Comment by suminwei2772** [comment]
In ~0+Treatment, you are parametrizing using the means from each condition (treatment vs. control). The hypothesis being tested is how different are the means.
For ~Treatment, you are looking at how much change there was in gene expression under cigarette treatment compared to control (parameters would be theta, tao). Hypothesis tested in this model would be how much change there is w.r.t. to control.

Both models seem valid to me.

For trying to get the number of probes satisfying fdr<0.05, I don't really understand what this fdr is telling us. Are the genes that satisfy this threshold significant genes? Or is it we still need to sort the data to find significant genes after we adjust for this false-positive rate?
 
p.adjust(datEBFit$F.p.value, method = "fdr") < 0.05 ---> I did this line of code for fdr. Why are we adjusting the F.p.value and not p.value?

**Comment by singha53** [comment]
@suminwei2772 

> DesignMat <- model.matrix(~ Treatment, meta_dat)
> datfit <- lmFit(dat, DesignMat)
> datEBFit <- eBayes(datfit)
> **topTable(datEBFit)**

The F.p.value is testing whether any of the coefficients (Intercept or Treatment) is different from 0. Since the intercept is always different, you will get almost all genes that are differentially expressed. You are computing the F.p.value because you have not specified any specific coefficient or contrast in your topTable via the argument coef.
-- see page 41/43: lecture-10: Statistical inference: large scale, limma, empirical bayes

To find genes differentially expressed between Treatment conditions look into the coef argument of topTable()
- page 42/43: lecture-10: Statistical inference: large scale, limma, empirical bayes
or see: example on:
- page 35/46: 	lecture-11: Statistical inference: multiple testing

>> For trying to get the number of probes satisfying fdr<0.05, I don't really understand what this fdr is telling us.

The FDR = F/S (F=# of false positives, S=# of significant hits): see page 10/46 from lecture-11: Statistical inference: multiple testing 
fdr<0.05 implies that given S number of significant hits (e.g. 100) than 5% of them are false positives (5/100). 

Are the genes that satisfy this threshold significant genes? Yes.

>>Or is it we still need to sort the data to find significant genes after we adjust for this false-positive rate? 

Please don't confuse false positive rate with false discovery rate. see summary on page 45/46 from lecture-11: Statistical inference: multiple testing

>> p.adjust(datEBFit$F.p.value, method = "fdr") < 0.05 ---> I did this line of code for fdr. Why are we adjusting the F.p.value and not p.value? 

The question is asking how many probes are associated with treatment so you are interested in a specific contrast.

Let me know if you have additional questions,
Cheers

**Comment by ppavlidis** [comment]
I don't think anybody answered this part?

> When you say "make a quantitative statement about presence of an outlier: e.g., quantify for each sample, whether it “sticks out” compared to the other samples," can we do, for instance, a fold change of that sample's expression value compared to the mean of the rest of the samples? What other sort of quantification would you suggest?

In the context of the homework question, use the correlations from the previous parts of the same question.

In general the definition of "outlier" can be made many ways. You could indeed look at the mean of each sample, and you could decide that some deviation be considered "outlier". But you'd need to make sure that was sufficiently sensitive or even appropriate. For example, if the data have been normalized, would the sample mean be a useful indication of sample differences?

I also want to stress (lest all this be taken out of context) in real life one would ideally define what would constitute an "outlier" before the experiment is performed, rather than poking around the data and deciding post hoc (after the experiment is done). Short of that ideal, declare outliers early in the data analysis process and remove them, and be firm about not going back and changing your mind (risk of data dredging - "let's remove/restore outliers iteratively until we get a publishable result").

**Comment by rbalshaw** [comment]
Further thoughts re: identifying outliers.

Don't forget that fold-change incorporates only one part of what we might want to consider in thinking about outliers.  You probably haven't, but it's good to be careful with these ideas.

The other part of the notion of outlier would be the within-group variability (i.e., the variability of the residuals from your modelling).  If a point were "a long ways out "(in terms of fold-change) but that particular gene/protein/whatever were to have been especially variable then the large fold-change is less "important".   A measure of the fold-change over the corresponding standard deviation estimate is a good choice for this, in just the same way that the t-statistic is a good way to assess whether the fold-change between two groups of samples is "important".

**Comment by suminwei2772** [comment]
Thank you for all the detailed responses! I'll probably ask follow-up Qs later.

For Question 3.2, 
1) When taking the top50 hits, are we just taking the top50 based on unadjusted P-values?
2) I ran the following code to estimate false discovery rate of the Top50 list:

```
top50 <- topTable(datEBFit, number=50, coef = 2, adjust.method="none", p.value=0.001,sort.by="p")
top50_sort_treatment <- dat_sort_treatment_time[rownames(top50),]
localFDR <- lfdr(p = top50$P.Val)  
```

and got this error message: 

```
Error in pi0est(p, ...) : 
ERROR: The estimated pi0 <= 0. Check that you have valid p-values or use a different range of lambda.
```
Is there an issue with the P-values? What might the error be coming from?

**Comment by singha53** [comment]
For Question 3.2,
>> When taking the top50 hits, are we just taking the top50 based on unadjusted P-values?

can you elaborate on this? The answer is yes, but I am wondering what else you were thinking of ordering them by?

>> Is there an issue with the P-values? What might the error be coming from?

pi0eset --> is used to estimate pi0 (proportion of non-differentially expressed genes). But you are only putting in very significant genes (top 50). pi0 is estimated using the p-values of all genes; see slides 18-20 from lecture-11: Statistical inference: multiple testing.

However, for this question:
What is the (estimated) false discovery rate of this "hits" list? How many of these hits do we expect to be false discoveries?

you can compute the FDR = F/S. how would you compute F (# of false positives) and S (# of significant discoveries)? ie. of the 50 hits how many are false positives?

**Comment by suminwei2772** [comment]
Multiply average p value in the full list of probes by the total # of
probes, then divide by 50?

**Comment by singha53** [comment]
@suminwei2772 what do you mean by average p-value?

**Comment by oktokat** [comment]
Hi everyone!! @rbalshaw @singha53 @ppavlidis @farnushfarhadi @santina 

Alright, a couple of us are still having trouble with the quantification of the outliers. Here's what we know so far:
1. We want to know which samples stick out, because consistency in QC is important.
2. You can use mahalanobis distance in order to find outliers. From reading more about this method, it seems to be similar to a t-stat, giving you the distance of a point from the "centre" (mean?) in terms of sd.

Questions:
- Is this the right idea surrounding mahalanobis distance? The mostly helpful explanations I found were [here](https://eurekastatistics.com/using-mahalanobis-distance-to-find-outliers/) and [here](http://stats.stackexchange.com/questions/62092/bottom-to-top-explanation-of-the-mahalanobis-distance).
- Are we even on the right track with using mahalanobis distance? It seems to be an effective method but we didn't spend very much time talking about it in class, so if you have other suggestions/tips they'd be greatly appreciated! 

Thanks in advance and hope you're enjoying the nice weather today! :)

**Comment by rbalshaw** [comment]
I would say you are probably on track.

Mahalanobis distance (MD) between two points (or between a point and the mean for it's group) could be thought of as a multivariate generalization of what you'd get if you calculate the number of standard deviations between a point and the group mean for a single variable.

But, because we're talking about a multivariate generalization, you have to consider the "distance" in terms of the multivariate notion of the standard deviation -- meaning you have to consider the standard deviations of all the variables and their correlations at the same time.

Sounds awful, but is really pretty straightforward.  Those explanations you linked were pretty much on target -- though the second one got a bit heavy...  If I were waving my hands at a whiteboard, I'd draw a bunch of points in a sort of oblong football shape (North American football, not soccer) that was tilted at a bit of an angle to the x-axis.  

The MD considers the multivariate shape of the football when it calculates distances.  A point that was 30 cm away from the centre of the football but in the same direction as the long axis of the football shape could be about the same Mahalanobis distance from the centre as one that was only 15 cm away from the centre of the football but in the same directon as the *short* axis of the football shape.

**Comment by ppavlidis** [comment]
About outliers: Probably we have to revise this question in the future because it's left unclear what method we want to you to try.

The intention is, as stated,"based on the sample correlation matrices created in Q2a", and that holds for the rest of the question. You can get full credit without using any method like MD. The sample-to-sample correlation is adequate in this case to judge outlier-ness. In practice, as described in lecture, it works well and is very commonly used in genomics (PCA is another common approach).

I say this because I don't want all the students to go on that tangent trying to figure out MD - it's not that MD won't necessarily work, but that it wasn't intended by the question.

Whether MD catches outliers that correlation misses in genomics data is a question I don't know the answer to, because I haven't tried it enough. If someone has data that MD is superior, I'd be interested in seeing it! I've just never seen it used in routine genomics QC.

Now, in the example at the first link @oktokat gives, you can't use correlation because there are only two dimensions, and they can easily cook up a case where distance-from-the-mean fails. (I question whether they identified the right outliers with MD anyway -  but it's just an example)

**Comment by dakep** [comment]
Thanks @ppavlidis for clarifying. The conclusion I draw from this discussion about Q2.2 is that we should check for the presence of __samples with a different correlation pattern__ and not _outliers_. I think the word _outlier_ in the question is very unfortunate since it usually means something completely different.

Using MD or any other "common method" to find outliers in our data will give very different results than looking at the correlation matrix. Furthermore, computing the MD with the number of genes in our data is something we never discussed (and probably won't discuss) in class.

**Comment by oktokat** [comment]
Thanks @rbalshaw @ppavlidis and @dakep! 

Maybe I'm still confused on what method we're supposed to be using to answer this question.. what it sounds from this discussion is that we will look at the heatmap and find the samples that are different from the rest of the samples (eyeball it first). But then we're supposed to quantify the ones that stick out, now knowing that we don't need to use complex methods (MD). That said, further up in the discussion @rbalshaw noted that it is important to consider both the within group and between group (fold-change) variabilities. I'm not quite sure how to do this without using MD. I also understand that we're supposed to be using the sample-to-sample correlations, but I'm confused on what exactly are we doing with them. If someone could point me in the direction of a specific method (either in the slides or otherwise), I would be so appreciative!! 

Sorry for beating this question to death, I just feel like I must be missing something key to understanding what exactly we're supposed to be doing/answering. Again, many thanks to everyone who has contributed!

**Comment by ppavlidis** [comment]
@dakep Were you were reading "outlier = "problematic sample"? You're right, that's not exactly what we meant. The word "different" as you use it and "outlier" are meant to be approximately synonymous here. Just like "different", the word "outlier" doesn't mean much without context of "compared to what, and by what measure?" Sorry for the confusion.

We did briefly discuss using MD in lecture, lecture 5, page 20 of the notes, and what I said in lecture was that I wasn't aware of it being used much for QC in genomics (references to the contrary would be helpful); and that I tried it on the same data set in the examples, it didn't give very satisfying results. Again, correlation *is* a "common method" to identify problems in genomics data. I recommend it because it's simple, intuitive and effective.

**Comment by dakep** [comment]
@ppavlidis You are right that "outlier" without context does not mean much. I think the confusion only starts when people do a web search for "outlier detection", because that usually refers to finding samples that are contaminated or come from a different distribution (i.e., in the __sample space__).

We talked about using MD in the lecture, but to use the MD in this case we would have to estimate a approximately 23000 x 23000 covariance matrix and we haven't talked about that (when we only have 23 samples). But, as said above, using MD would find other points to be outlying anyways, since it refers to another definition of "outlier".

**Comment by ppavlidis** [comment]
@oktokat No problem, I'm glad you're asking questions.

Just sticking to correlation for this explanation (again, you can substitute in whatever measure you want if you don't like using correlation, but for this homework, you'll save everybody trouble if you use correlation):

* Quantitative just means using the correlation values, not just the heatmap colours.
* Within-group means within a set of biological replicates.
* "Sticks out" is indeed a judgement call, but can you think of a working definition that aligns with what you see in the heatmap? How about "the sample that has a lower correlation with all the other samples in its group, than any other sample has?"

(As the questions says "examine [a questionable sample] in the context of its experimental group")

So let's say we have a simple data set with 6 samples, supposedly 3 of group A and 3 of group B. Looking at the correlation values, the pairwise correlations among group A are all around 0.9 (let's just say that "around" means within say 0.05). Within group B the correlations are all around 0.9 except for one sample that has a correlation of 0.7 with the other two. I hope you can picture this.

Comparing samples from group A to samples in group B, you also see correlations around 0.7. What Rob means is that shouldn't be treated as problematic, because you might be expecting group A and group B to be very different.

And say the sample in group B that has a correlation of 0.7 with its group-mates has a correlation of 0.9 with the samples in group A.

If I saw this, I'd immediately wonder if there was something wrong. We have a sample in group B that looks (on the basis of correlation) like it belongs in group A. This would send me back to lab notebooks etc. to see if that was plausible. I might find that this weird sample is actually not a bad sample, but came from group A. And so forth. The action taken in the end depend on the situation (and on closer inspection than I'm describing)

A different scenario would be where that sample has a correlation of less than 0.7 with *all* the samples (not just within its group). That would suggest something is "outlier-y" about the sample for the whole data set.

**Comment by oktokat** [comment]
@ppavlidis THANK YOU! This is what I started to do after your last post, and this makes it way more clear. Much appreciated :)

**Comment by ppavlidis** [comment]
@dakep Ah, I see the confusion - to be clear, we _are_ talking about the sample space. We were discussing using MD instead of correlation, but still for the samples (comparing samples to each other). See my last post to @oktokat, it is indeed about detecting possible contaminated samples and the like.

Doing a quality assessment for genes with MD or correlation definitely doesn't make sense, since we don't expect genes to be globally similar to each other in any data quality sense (they have different expression levels, have different expression patterns, etc.).

I'll talk about gene correlations in a later lecture - it has a biological interpretation.

If you google around enough, you might come across a paper that talks about "outlier genes" that basically maps to "differential expression", but that's a very idiosyncratic usage (to put it nicely).

**Comment by dakep** [comment]
@ppavlidis I know we are talking about "outliers" in terms of "samples that appear strange". What I meant with _outliers in the sample space_ is that when you look at correlations, you are no longer in the _sample space_ (in the mathematical sense). You look at the samples from a "different angle" if you use the correlations, which is not in line with most "outlier detection" methods.

**Comment by ppavlidis** [comment]
@dakep OK I think I understand what you are getting at. But not sure. 

Both MD and correlation are statements about sample vectors. (If you don't like correlation, use Euclidean distance instead). Correlations are "in the sample space" just as much as MD is.

The main difference I see is the MD approach gives you a value that can be interpreted in isolation, since it's in terms of SDs from the estimated multivariate mean or something like that. That definitely sounds nice in principle and that is probably the motivation of many outlier detection methods - that it just gives you one number to look at for each sample.

The correlation doesn't have that inherent property, but conceptually the approach is very similarly motivated - using distance/similarity among samples. PCA is another very common way to look for outliers that has the same basic idea.

This is a bit of a digression from the original issue topic, I'd be happy to continue a discussion about the merits of different outlier detection methods elsewhere.

Open a new issue for new questions, thanks!
