### ISSUE TITLE
Question 2.1

### ISSUE THREAD

**Issue by oktokat** [STAT540-UBC/Discussion#140]
@farnushfarhadi @santina @singha53 @ppavlidis @rbalshaw 

Hey all, 
This is a pretty rudimentary question, but I'm having trouble on getting started on 2.1 in the assignment. (I read the previous issue about it, but it didn't really answer my question)

When we create a sample-sample correlation matrix, I'm assuming that means we make a heatmap each sample on the bottom (x-axis) and each sample on the side (y-axis). But what does each box in the heatmap represent? Is it the gene expression of ALL genes within a sample compared to the gene expression of ALL genes in another sample? Intuitively that doesn't seem helpful in understanding the data for some reason. 

I worked through the seminars and looked back at the examples of heat maps in the lectures, but most of them plot genes on one axis and samples on the other axis. But with our 22k genes that seems excessive/not super helpful either.

Any hints, tips, tricks on how to get started would be much appreciated :) 

Thanks in advance and happy family day!

**Comment by singha53** [comment]
@oktokat 

**>> But what does each box in the heatmap represent? Is it the gene expression of ALL genes within a sample compared to the gene expression of ALL genes in another sample?**

Yes. 
e.g.
dat <- matrix(rnorm(200000*10), nrow=20000) # expression dataset (pxn)
corMat <- cor(dat)  # correlation matrix (nxn)
dim(corMat) # 100 x 100
corMat[1,2] # correlation between sample 1 and 2
cor(dat[,1], dat[,2]) # correlation between sample 1 and 2
corMat[1,2] == cor(dat[,1], dat[,2])  # TRUE

**>> Intuitively that doesn't seem helpful in understanding the data for some reason.**
Samples that are similar should have higher correlation values (similar gene expression) compared to samples that are different. Suppose you obtain blood samples from 5 healthy individuals and extract the RNA, making 2 aliquots from the RNA from each person. Then you run whole genome expression profiling for the 10 RNA samples (2 technical replicates from each person). When you create the correlation matrix, you should expect to find that the technical replicates from each person are more similar than between person. If you create a correlation matrix and order by Subject, you should see this. This same effect goes for other variables such as Time, batch, treatment etc. 

see slide 39/49 from lecture-4: Exploratory data analysis. Note: the expression dataset is not ordered, so you will have to do that for question 2.1.

Let me know if you have additional questions.
Happy Family Day to you too.

**Comment by farnushfarhadi** [comment]
Hi @oktokat 

Thank you for asking question! 

- Sample-sample correlation matrix with size N by N (N is the number of your samples) represents the correlation between samples. So as you said, heatmap would have ALL N samples in x-axis and ALL N samples in y-axis. Each `box [i,j]` in heatmap addresses the correlation between sample `i` and sample `j`. 

- Representing overall gene expression levels across samples is another use of Heatmaps. But as you noticed, it is not working out with 22K genes. Usually we come up with our genes of interest (I.e. genes that are differentially expressed in condition 1 vs condition 2) and then we plot their expression levels to see the changes.

**Comment by farnushfarhadi** [comment]
@singha53 I just saw you answered. Thanks

**Comment by ppavlidis** [comment]
@oktokat To help understand the underlying idea, I suggest that you start by making scatter plots of any two samples against each other (one point = 1 gene/probe/whatever). Then the idea of "correlation between the samples" might be clearer. Think: if two samples have a correlation of 0 what would that look like in the scatter plot, and what would it mean? Is it possible or reasonable for two samples to have a correlation of -0.5? If I told you the correlation of two samples was 0.8, would you be able to picture what the scatter plot *might* look like?

You should eventually see that the correlation between the samples is a summary of what the scatter plot shows. Because it's a summary it doesn't tell you everything that the scatter plot does (so there's no unambiguous answer to the last question I give above), but the nice thing about summaries is they summarize :)

It's important that you get what the sample correlations are, as it's essential to understanding the multivariate methods like PCA, clustering and prediction methods that we're coming to soon. But the sample correlation heatmaps are also a valuable QC/exploration by themselves.

@singha53 mentioned that "Samples that are similar should have higher correlation values". That's true but I want to make sure we don't over-emphasize this as a necessary outcome of the correlation heatmaps. As you seem to appreciate, because it's using all the genes, its about the overall properties of the dataset and completely misses anything that might be happening at the level of single genes. It's very possible to look at the sample correlations and have no obvious sign of the "subgroups" of samples (that is, all the samples have about the same correlation with every other sample). But that doesn't rule out the possibility of more subtle patterns existing that the correlation summary misses. 

And even when subgroups are apparent, the difference in correlations will often be smaller than you might be thinking. The difference between samples from different tissues vs the same tissue could be a correlation of 0.8 vs. 0.9, and this will be completely obvious in the heatmap if you set it up right.

**Comment by oktokat** [comment]
Wow, THANK YOU so much for these in-depth answers!! Much appreciated!!
