### ISSUE TITLE
Assignment Q5

### ISSUE THREAD

**Issue by suminwei2772** [STAT540-UBC/Discussion#142]
@ppavlidis @santina @farnushfarhadi @singha53 
Sorry for bombarding you all with assignment questions!
I might be totally wrong about this...but for Question 5, is this a case where we'd have to form contrast matrices consisting of different comparisons between conditions  (ex. Treatment vs control) and looking at interaction effects? 
Would you suggest doing decideTest()? It seems to me that doing topTable for testing each comparison might be sufficient to address the questions.

**Comment by farnushfarhadi** [comment]
@suminwei2772 Thank you for asking question. I believe your questions are helpful for everybody. 

>> is this a case where we'd have to form contrast matrices consisting of different comparisons between conditions (ex. Treatment vs control) 

First try to build your design matrix that would propose coefficients for: 

- main effect of Treatment 
- main effect of Time 
- interaction effect of Treatment and Time

Then if your comparison of interest is not represented in your design matrix, you would need to build a contrast matrix ... 

>> Would you suggest doing decideTest()? It seems to me that doing topTable for testing each comparison might be sufficient to address the questions

For any of the comparisons, topTable (or topTags) would give you statistics that you need to infer your hits.

**Comment by farnushfarhadi** [comment]
@singha53 Please feel free to add your in-depth answers cause they are always needed! :)

**Comment by singha53** [comment]
@farnushfarhadi lol. 

I'll just add that question 5 can be answered using either method: referred to as "cell means" and "ref + tx effects", see slide 29/50 from lecture-7: Statistical inference: more than two groups and slide 16/66 from lecture-8: Statistical inference: linear models. "cell means" is alot more flexible since you control the contrast matrix.

ref+tx effects
“it’s a 2x2 factorial design” - lm(y ~ thingA * thingB)

cell means:
“it’s just 4 groups”
lm(y ~ grp)

The interaction effects using the ref + tx effects is covered on page 18/66 from lecture-8: Statistical inference: linear models.
The interaction effects using the cell means is covered on page 44 from the limma user guide (http://www.bioconductor.org/packages/devel/bioc/vignettes/limma/inst/doc/usersguide.pdf), where it refers to the interaction as the  difference of differences.

Ill simulate an example for a 2x2 factorial design (similar to one in the lecture notes and limma user guide) to show you.

```
library(limma)
p <- 20000
b0 = sample(seq(4, 16, by = 1), replace = TRUE, size = p)
diffBetas <- seq(-0.4, 0.4, length.out = 100)
betas <- lapply(1 : 3, function(i){
  sample(diffBetas, replace = TRUE, size = p)
})

n <- 100
time <- factor(rep(c("pre", "post"), each = n/2))
trt <- factor(rep(rep(c("A", "B"), each = n/4), 2))

genEset <- matrix(0, nrow = p, ncol = n)  # p x n gene expression matrix
for(i in 1 : nrow(genEset)){
  genEset[i, ] <- model.matrix(~time*trt)%*%matrix(c(b0[i], betas[[1]][i], betas[[1]][i], betas[[1]][i])) + rnorm(n)
}

# reference treatment effects
design <- model.matrix(~time*trt)
fit <- eBayes(lmFit(genEset, design), robust = TRUE)
top.int1 <- topTable(fit, coef = "timepre:trtB", adjust.method = "BH", n = Inf)

# cell-means  (4 groups)
grps <- paste(time, trt, sep = ".")
design <- model.matrix(~grps + 0)
contMatrix <- makeContrasts(Interaction = (grpspost.A-grpspre.A)-(grpspost.B-grpspre.B),
  levels = design)
fit <- lmFit(genEset, design)
fit <- eBayes(contrasts.fit(fit, contMatrix), robust = TRUE)
top.int2 <- topTable(fit, coef = "Interaction", adjust.method = "BH", n = Inf)

## compare logFC (coefficients) and BH-FDRs
par(mfrow = c(1, 2))
plot(top.int1$logFC ~ top.int2$logFC, 
  main = "Interaction-logFC", ylab = "ref+trt", xlab = "cell-means")
abline(a=0, b=1, col = "red")  # identity line (y=x)
plot(top.int1$adj.P.Val ~ top.int2$adj.P.Val, 
  main = "Interaction-BH-FDR", ylab = "ref+trt", xlab = "cell-means")
abline(a=0, b=1, col = "red")  # identity line (y=x)

```

![image](https://cloud.githubusercontent.com/assets/8978305/22954326/ae75935c-f2ca-11e6-96b9-1eaab272f5de.png)

Please note: Nothing I have stated is outside of the lecture notes (the limma user guide was made reference to in the notes).
Cheers.

**Comment by suminwei2772** [comment]
Thanks @singha53 and @farnushfarhadi  for your help!
Also, are we assuming all models are linear models, or are we assessing quadratic models are well?

**Comment by singha53** [comment]
The quadratic model is a special case of the linear model: see page 21/56 of lecture-9: Statistical inference: linear models.

Other sources:
![image](https://cloud.githubusercontent.com/assets/8978305/22998101/28b3bc10-f38a-11e6-95c6-3a8e8d6d70ff.png)
https://en.wikipedia.org/wiki/Linear_model

Examples in R: http://www.theanalysisfactor.com/r-tutorial-4/

**Comment by abaghela** [comment]
Hello, 
I just wanted some clarification on question 5.3 - Plot a few probes where the interaction does and does not matter.

What exactly does this mean? I have DE genes from when I did topTable for the Treatment and the Overall effects. Are probes where interaction matters just probes that are ONLY in the overall effect list, whereas probes where interaction does not matter are all other probes?

I have figured out how to make the plots on test probes, I just don't know which ones to use at this point.

Thanks, 

Arjun

**Comment by singha53** [comment]
@abaghela What do you mean by this? "topTable for the Treatment and the Overall effects", the interaction column in the design matrix? For your topTable you will have a list of genes ranked based on BH-FDR (for example). the probes that matter (significant) are the top of the list whereas probes that do not are at the bottom (not significant).

**Comment by abaghela** [comment]
@singha53 Ok, that makes sense. Thanks!
