### ISSUE TITLE
Which way to make design matrix

### ISSUE THREAD

**Issue by abaghela** [STAT540-UBC/Discussion#153]
* I emailed this question to @santina , who told me to post it here. 

There are two ways to make the design matrix according to limma. 
This way seems to make sense to me: 

testing <- model.matrix(~0+Treatment, meta)
colnames(testing) <- c("CS", "Control")

#### Now fit the linear model on the data.
fit <- lmFit(data, testing)

#### To make pair-wise comparisons between the groups, a contrast matrix can be created.
contrast.matrix <- makeContrasts(CS-Control, levels = testing)
fit2 <- contrasts.fit(fit, contrast.matrix)
fit2 <- eBayes(fit2)

This way differs from the rest, because I have done (~0+Treatment, meta), rather than (~Treatment, meta). 

Is there a difference. I am confused!

Thanks, Arjun

**Comment by rbalshaw** [comment]
You might try simplifying.  Try using only one outcome measure and analyse using lm().  

Might help clarify whether these two approaches can be made to agree...

**Comment by singha53** [comment]
@abaghela see my answer to a previous post: 
https://github.com/STAT540-UBC/Discussion/issues/142
A

**Comment by ppavlidis** [comment]
@abaghela Reading #142 is going to help you, but I'm not sure what you mean by two ways to make a design matrix, you only mention one (though you mention two different model parameterizations).

**Comment by santina** [comment]
You can do both, either with the ref+treatment effect design matrix or with contrast matrix made from the cell mean matrix. You're on the right track with using contrast matrix (See slide 35 in lecture 10.). Using your method or the others' method with (~treatment, meta) would give the same result. It's just two different ways of thinking about the same problem. (See slide 29 lecture 7).   

Just to clarify 1) design matrix vs contrast matrix, and 2) the difference between making these two design matrices:
1. `testing <- model.matrix(~0+Treatment, meta)`
2. `testing <- model.matrix(~Treatment, meta)`

2) See #142 and also slides 34. 47-49 of lecture 7.  In the first one, you're using cell means, and using 0 as your intercept. Thus your null hypothesis is that the means of those developmental stages are zero. In the second one, you're saying there's an effect from a reference dev stage (the first stage) to all the other dev stages. That's what we meant by the first one is "cell means" and the second one has to do with "reference + some effects". 

1) So that's design matrix. Now let's talk about contrast matrix, which is about the pair-wise comparisons between groups. In this case, whether the difference between cigarette and control is zero.

**Comment by abaghela** [comment]
Thank you everyone! Very helpful.

**Comment by santina** [comment]
@abaghela 

You asked me about whether releveling your metadata make a difference for Q5 where it asks for a full model. It shouldn't. I just tested on my computer and I have the same result whether I did
`NHBE_des$Treatment<-relevel(NHBE_des$Treatment, ref="control" ` or not. 
Idk why you get different results when you relevel. Perhaps you didn't specify the right coefficient?  (it would be Treatmentcigarette_smoke instead of Treatmentcontrol)
