### ISSUE TITLE
Analysis Assignment  - Part2

### ISSUE THREAD

**Issue by rasiimwe** [STAT540-UBC/Discussion#168]
@santina @farnushfarhadi 
Hi profs :-) should we have part2 of the analysis assignment as a continuation of part 1 or should we start a new file?

**Comment by santina** [comment]
You can put it as a continuation of the part 1 :)

**Comment by rasiimwe** [comment]
@santina  Okay, thanks!

**Comment by santina** [comment]
I mean you can do either. But if you plan to improve your mechanics for part 1, make sure to put them together as one single file (continuation of part 1). We are grading mechanics for the assignment as a whole.

**Comment by rasiimwe** [comment]
On Qn 6.1 i am trying to plot a heatmap of the first 100 genes and I keep getting the error x must be numeric. 
Kindly help me understand this error. 
Thanks

I am using:

#heatmap(exprs(data2[2:101,]))# using 2:101 because 1 row has variables c and b

data2minusrow1 <- data2[-1,]
cormatrix <- cor(data2minusrow1)# creating a correlation matrix on my data data_frame

first100 <- head(cormatrix,100)

heatmap(first100, symm= FALSE, trace = "none", cellwidth = 10, cellheight = 10, main = "Colored clusters" )

**Comment by ppavlidis** [comment]
I'm assuming you mean `heatmap` is giving you that error, and that your `data` is oriented so that cormatrix is the correlations among your samples. But I'm wondering if you are looking at the correlation of genes for some reason? That shouldn't be necessary. I'm not totally sure what part of the homework you are doing, but one question is to look at the data itself for 100 genes. Not the correlation matrix.

Anyway: Here is some general debugging advice. I strongly (very strongly) suggest that whenever you have a problem like this, you should look carefully at the error message and then inspect the source of the error. In this case, it's about x, and x=first100. But if you don't understand the error message, just [do a search](https://www.google.ca/webhp?ie=UTF-8#q=error+x+must+be+numeric+heatmap&*).

The other general debugging advice is you need to inspect your inputs. Are you sure `first100` contains what you think it does? Did you look at it?

**Comment by rasiimwe** [comment]
@ppavlidis 
Thanks for the advice. I tried searching and so far the options I got didn't help. Let me keep searching. I suspect though that my inputs were delimited by commas or came in as a string so I trying this too.
Thanks.

**Comment by ppavlidis** [comment]
OK I'm glad you understand the error message. It's impossible for us to guess at a specific solution. I mean, again, have you looked at `first100`? Is it non-null?

**Comment by rasiimwe** [comment]
@ppavlidis 
I have finally solved my problem. After 7hours! 
My system also seemed not to appreciate the .tsv file which I noticed later on. But I fixed this too. Thanks

**Comment by ppavlidis** [comment]
What was the explanation?

**Comment by rasiimwe** [comment]
@ppavlidis 
Just for the part of the file - when i downloaded my file, it automatically took on the .txt extesion. So it became GSE37599-data.tsv.txt. In my working directory I called it GSE37599-data.txt!

so instead of this:
<img src = "https://github.com/STAT540-UBC/zz_asiimwe-rebecca_STAT540_2017/blob/master/Analysis%20Assignment/Analysis_Assignment_files/table1.png">

I was getting this:
<img src = "https://github.com/STAT540-UBC/zz_asiimwe-rebecca_STAT540_2017/blob/master/Analysis%20Assignment/Analysis_Assignment_files/table2.png">

But I fixed it by calling the file directly from its online source and appending the "header = TRUE" argument which I wasn't using initially.

**Comment by rasiimwe** [comment]
@ppavlidis 
Just for the part of the file - when i downloaded my file, it automatically took on the .txt extesion. So it became GSE37599-data.tsv.txt. In my working directory I called it GSE37599-data.txt!

so instead of this:
[<img src = "https://github.com/STAT540-UBC/zz_asiimwe-rebecca_STAT540_2017/blob/master/Analysis%20Assignment/Analysis_Assignment_files/table1.png">]

I was getting this:
[<img src = "https://github.com/STAT540-UBC/zz_asiimwe-rebecca_STAT540_2017/blob/master/Analysis%20Assignment/Analysis_Assignment_files/table2.png">]

But I fixed it by calling the file directly from its online source and appending the "header = TRUE" argument which I wasn't using initially.

**Comment by ppavlidis** [comment]
Please let me know what happened with your "non-numeric" issue. I feel sorry that you wasted many hours on what is probably a very simple problem. And you didn't say anything about why you are looking at a correlation matrix in that part of the assignment.

Your linked images are broken, so I don't see anything - can't you just put in the text you are getting in the R console?

But I don't know why you are mentioning the file name - the file name does not matter at all in R. You could call it `data.csv` or `nottabbed.xls` or `data.doc` or even just `data` and you can *still* read it in as a tab-delimited file. Read the documentation about `read.csv, read.tsv, read.table, read.delim`. File names are not important if you understand what these functions do (and since they are used a lot, I strongly recommend that!)

If you are getting a "file not found" error (and I don't know if you are), that's a clue that you're putting in the wrong file name (or the file doesn't exist). 

If the problem is with your operating system, that's another story, but files are files. One tip is to make sure you have "show file name extensions" turned on so that when you look at them in your Windows or Mac file browser you see `foo.txt` and not just `foo`. But within Rstudio, I think it shows the full file name, so it doesn't really matter (and again, R only sees the full file name).

If you press `tab` while you are typing  a file name into an R source file or console, it will give you suggestions, just like it does in suggesting functions, objects and variables.

These fundamental computer skills have to be mastered before you can address more complex issues of statistical analysis, it takes practice!

**Comment by rasiimwe** [comment]
@ppavlidis 
Hi Paul, The main problem was that I did not specify the "row.names = 1" argument when I was calling in the file. The file was actually okay but I was looking at all possible causes of the problem, I changed the code around, tried so many things but it was just that I didn't call the row.names argument!!! Wow! I will not forget this :-)  

My first data frame looked like this
V1  V2  V3  V4  V5  V6  V7   -->  (column names)
      b1  b2  b3   c1  c2  c3  --> row 1
the second row in the table started with the expression values

The corrected frame:
b1  b2  b3  c1  c2  c3  --> column names
1st row starts with expression values

I dont know whether this is clear, sorry the screen shots were not visible.

**Comment by ppavlidis** [comment]
A common mistake; this would have been obvious if you just looked at the data. I *always* do something like `head(data)` the minute I have any suspicions about my data.

One of my big lessons to students in this course is to look at your data, this is an example of what can go wrong if you don't, so you learned the lesson :)

**Comment by rasiimwe** [comment]
I "looked" at the data but didn't know/ think that the first row appearing like this would have such repercussions.  Lesson learned :-). I will do more than looking. 
Thanks for the helpful and prompt feedback.

**Comment by ppavlidis** [comment]
That makes sense, sorry to assume you hadn't looked - but if you had shown the data to us we could have spotted it immediately. Your original request didn't have enough information. I'm sorry again you wasted so much time!

**Comment by rasiimwe** [comment]
@ppavlidis 
I will provide more details next time.
Many thanks.

**Comment by rasiimwe** [comment]
@santina @farnushfarhadi @singha53 
Hi 
In Question 7.1 we have a section that reads:

"What are dimensions of the dataset? In addition to reporting number of rows and columns, make it clear what rows and columns represent. What is the difference between the rows of this dataset versus rows of the array data in **question 1a**?"

Does question 1 here refer to question 1 in the first part of the assignment or does it refer to question 6?
Thanks

**Comment by santina** [comment]
Woah... It should be 6. The second part is completely independent of part
1.
Sorry for the confusion.
