### ISSUE TITLE
Some guidance on the assignment Q6-Q8

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#170]
@STAT540-UBC/students 

## Notes on your assignment part 1 

We are pretty much done with grading it, but we just still need to post them. Anyhow you have the solutions so that would help with the second part. **Don't forget that you can work on improving the mechanics of the first part and we will grade that together with the second part.** 

### graphing 
It's very important that you interpret these plots besides just making them. 

- (High volume) scatter plot matrix
   - check out ggpairs() from GGally 
- A heatmap of the first 100 genes
   - Very similar to what you did with heatmap in part1, when you do heatmap for the top50 genes. 
- Compute the Pearson correlation of the samples and plot the results using a heatmap.
   - Very similar to assignment part 1 as well 
- Scatterplot the six data samples with respect to the first two principal components and label the samples.
  - see the PCA part of seminar 9. 
  - If you use `prcomp()`, make sure to give it the tranpose of your data, and of course scale and center the data because prcomp does scaling and center column-wise. Since you want to center and scale along the gene expression across the samples, you'd want to transpose the data 
  - the output would give you a list, in which x is the matrix you want. 

## Q7: VERY IMPORTANT 

For using edgeR,, please look at [this example](https://github.com/STAT540-UBC/demo_santina/blob/master/RNASeq/seminar7_rnaseq.md) or the edgeR manual for steps on normalization and filtering because [the seminar 7](http://stat540-ubc.github.io/seminars/sm07b_RNA-seq.html) doesn't have those steps.
 
Instead of using 3 separate functions for dispersion (like in the seminar), you could simply use one function 

```
count.glm.tag.disp <- estimateDisp(dge.glm, design_matrix)
```

This is probably because the seminar was written before the latest update of edgeR.  
Let us know if you have any question.

**Comment by wvictor14** [comment]
Hi @santina 

Is it necessary to do a log transformation on your data before filtering based on read counts? In the edgeR manual example in the filtering section, they don't. However, in your github example, you do. Not sure why this would be important at this step since you are filtering based on an specific threshold.

Thanks,
Victor

**Comment by ppavlidis** [comment]
For filtering it doesn't matter whether you filter on `threshold` or `log(threshold)` as long as the data are the same way. My understanding of @santina's code is that she's working with log-transformed counts (call to `cpm`) and a log-transformed threshold (declaration of `threshold`).

For the actual differential expression analysis, edgeR and other count-specific methods should work on counts, not log-counts. 

But later on in Santina's code I'm not sure what happens - does the DGEList keep track of whether the values are log-scaled? It seems it does. When I've used edgeR I just use plain counts so I didn't think about this.

(voom-limma is different since it works with log-cpm)

**Comment by wvictor14** [comment]
Ok great thanks. 

The DGEList objects has a slot for a 'counts' data frame, and she log-transformed that, and adjusted her threshold accordingly. (also not sure how threshold = log2(2.7*5) is supposed to equal 5 counts on log-transformed data, when the smallest lib. size in the samples is 2.7 million.). 

I also am having troubles understanding what exactly the 'dispersion' is and why is it important to estimate these parameters before fitting a model. Very generally, I interpret dispersion as something equivalent to the variance or standard deviation, in the sense that it contains some information about the spread of the data, except dispersion takes into account the mean, so different datasets (genes) variances can be compared. However, it's not clear to me why this quote makes sense 

> Only when using tagwise dispersion will genes that are consistent between replicates be ranked more highly than genes that are not. It has been seen in many RNA-Seq datasets that allowing gene-specfic dispersion is necessary in order that differential expression is not driven by outliers.
-edgeR manual p.17

Could you help clarify what 'dispersion' is and why it is useful to calculate it beforehand? Also, why doesn't edgeR do this 'under the hood' in the glm function if it is so useful / standard. When would you not ever not calculate the dispersions?

Thanks,
Victor

**Comment by ppavlidis** [comment]
I'll let @santina answer that question about DGEList and her code.

You're right that there's never a point in not estimating the dispersions. My impression is these things are broken up in steps for partly historical reasons - that they were testing many different ways of computing them, so they had a separate step, and even when they figured out the "best way" they left it as a separate step - partly in case they could change it easily again. At least, if I was writing the software, that would be my justification - I'm just guessing.

Estimating the dispersion is part of fitting the model, it just might seem unusual to do it as a separate step, but it makes sense overall. It's a little like the eBayes step in limma because the per-gene dispersion estimates are shrunken to a prior (to the global 'common' value, as I recall). The dispersion is a parameter in the negative binomial distribution. I recommend reading the edgeR paper(s) to get the details, and it's in the relevant lecture too (see also references at the end including lecture notes from Mark Robinson). You can think about it as how much "extra variance" there is on top of that due to sampling alone (which would follow Poisson statistics). In edgeR they interpret this as "biological variation", but that interpretation isn't required; the actual criterion is how well the method works. Adding that in fits the data better than Poisson.

The gene-specific dispersion bit is talking about whether you can just estimate a dispersion for the entire data set, or whether you need one for each gene. It might also be confusing that they use the term 'tag' when what they mean is 'reads for a gene'. 'tag' is a holdover from SAGE.  

I googled a little to see if there are any other easy-to-understand explanations, [this](http://seqanswers.com/forums/showthread.php?t=5591) comes up - from one of the EdgeR authors - warning: it's not recent, I'm sure there are many other such sources.

I hope that helps a little!

**Comment by santina** [comment]
Hi @ppavlidis and @wvictor14 

Thank you for the explanation on dispersion, Paul! 

I wasn't sure if log transform is needed, but I did it because I remember it from the lecture. 
Since it seems from Paul that like you can just work with counts in edgeR, and it's not done in the manual. I removed the log transformation, and changed the threshold accordingly. It's less confusing now. 

[edgeR manual](https://www.bioconductor.org/packages/devel/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf) p12 says to filter by 5-10 cpm.

**Comment by abaghela** [comment]
Hello, 

I had a question about filtering. If I filter low count genes with cpm (edgeR manual) in the deep counts, should I also be filtering for the low count analysis. I am following the edgeR manual, which states "a count of 5-10 in a library to be considered expressed in that library". I do not want to remove too many low expressed genes in the low count analysis, but I do want to stay consistent between the deep and low count data. 

Thank you.

**Comment by santina** [comment]
Yes, though you'd have a less strigent filtering for the low count because the library size is smaller in the low-seq

**Comment by nolanshe** [comment]
@santina  

In the link you have provided for  Q7, you write the following: "According to the manual, we would drop off the genes that aren't present in at least one sample for any of the conditions and filter with CPM (count-per-million) instead of the rare counts so that we're taking the library sizes into account". If I am understanding that correctly, then this says that we should exclude genes for which there exists a condition (there are two conditions in both the example and our assignment) in which there is at least one sample that falls below the threshold. Doesn't this mean that the "keep <- keep >=10" filter is incorrect? Shouldn't we only keep genes for which no samples in any condition are missing (i.e. keep >=21 for the example and keep >=6 for our assignment)? If that is not the case, then I have no idea what you mean by the first statement.

**Comment by farnushfarhadi** [comment]
I guess the intuition is 'I let the gene to be low expressed in at most all samples in **one** condition'  so in the example we have 10 and 11 samples for two conditions and we get the minimum number which is 10 and would like to keep a gene if it _not_ low expressed in 10 samples . In our case it is 3 (batch condition) and 3 (chemostat condition), so we can say keep >= 3. Does that make sense?

**Comment by annizubc** [comment]
@santina do we need to use both edgeR and DESeq2? or one of them is fine

**Comment by farnushfarhadi** [comment]
@annizubc only edgeR is fine

**Comment by nolanshe** [comment]
Ohhh okay yep that wording makes so much more sense. Thank you!

**Comment by santina** [comment]
Question asks for edgeR, so use edgeR.  Feel free to try out DESeq2 if you want though :)

**Comment by wvictor14** [comment]
@ppavlidis Thanks for that link on explaining dispersion. Was very helpful 👍
