### ISSUE TITLE
RNA vs mRNA data?

### ISSUE THREAD

**Issue by missleung** [STAT540-UBC/Discussion#204]
Hi guys,

I'm quite noob in terms of biological terms. I was wondering if anyone has read the paper for our paper critique assignment? The way they collected data seem to be quite complicated, and I'm having trouble understanding what they did. In the paper, they said that they have taken mRNA from the cells using Illumina in the 4 developmental stages and were counted. That made sense. But the next thing you know, they said they taken RNA data to generate cDNA in a totally different developmental stage. So my question is..can someone identify what these differences are? 

@emmagraham

**Comment by ppavlidis** [comment]
Good question - because it's definitely not very clear as presented. Assuming you are referring to the section on RT-PCR. So far as I can tell that cDNA was used for probe generation in the in situ hybridization. That RT-PCR section is not relevant to the RNA-seq. However, cDNA *is* made during RNA-seq library preparation, along the way.

I hope that helps but feel free to ask more questions.

**Comment by missleung** [comment]
Thank you Paul! Yes, I was referring to the RT-PCR section. That definitely answered some questions!
