### ISSUE TITLE
Is this a sufficient hypothesis ?

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#21]
I have a good dataset representing RNA gene expressions of CD4+ T cells, extracted using Nanostring  technology (found here: http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60341). These cells were stimulated by IFNb or Th17 polarizing cytokines.

Is it sufficient to state a hypothesis that asks, is there a fundamental difference between RNA gene expressions of cells stimulated with IFNb and those stimulated with Th17 ?

Also, in the proposal, do we have to describe IFNb, Th17 , cytokines, and  CD4+ T keywords in detail ?

Thanks!
@gcohenfr , @wdurnoUBC , @aliceZhu

**Comment by kmnip** [comment]
I am just your peer. So, please take this with a grain of salt.

It would probably be best to justified why those two were selected. In addition to the paper of the GSE, did any previous studies persuade you to pursue in this direction?

I think we must show our instructors and TAs that we are not blindly selecting certain datasets at random and testing for statistical significance. In particular, how would our hypotheses and the proposed analyses work address one or more biological questions?

You probably might need to justify that differential gene expression mean something in the context of CD4+ cells. So, it makes your statistical analyses (to support/reject the hypothesis) worthwhile...

**Comment by dtebaykin** [comment]
Hi,

My group has initially had a similar goal in mind - we were looking at the differential expression of certain genes in cancer vs normal tissue samples. The TAs told us that this type of analysis would be too simple and we should consider including metadata (experimental conditions information) into the analysis and trying to answer more sophisticated questions.

Hope that helps.

**Comment by wdurnoUBC** [comment]
@IssamLaradji , it is good to avoid simply running mass batches of t tests. To demonstrate the value and your understanding of linear models, it would be nice to have another factor. Perhaps your experiment has meta data? It could be something as simple as gender.

@kmnip , there is value to a motivated analysis. At least be able to infer the impact of your results.

**Comment by IssamLaradji** [comment]
@wdurnoUBC , so the linear model will be there to predict whether the RNA expression represents the T cells that are being stimulated by IFNb or Th17 ? right ?

or is there another interesting finding we can make using the linear model ?

**Comment by wdurnoUBC** [comment]
Yes @IssamLaradji , using a linear model to test for differences between two conditions (like IFNb & Th17) is a valid application. However, it hardly motivates upgrading from a t test to a linear model. Some of the best value from a linear model comes from its ability to model (& estimate for) several regressors simultaneously.

Now, I've taken a look at your posted URL. There's a ton of metadata there. You won't have trouble picking additional regressors if you would like. Just go down to samples, click on "[+] More", click on any sample and you'll find a section called "characteristics". There's plenty of data there on gender, ethnicity, etc.

Now why would you want to model several regressors simultaneously? Because they may both have effects! Let's use an example. Let's say gender was actually a very influential variable in your study. Let's say it's so influential that it makes differences between your experimental conditions (IFNb & Th17) undetectable. By modelling the effect of gender, you get a test which may then be more capable of rejecting your null when it is truly the case.

**Comment by IssamLaradji** [comment]
Thanks a lot for the great details!

**Comment by gcohenfr** [comment]
Agree with comments posted by @wdurnoUBC. Also, keep in mind that as the course evolves, you will learn other concepts and methods that you may want to use in your data other than testing for differential expression. Thus, going back to the point made by @kmnip, the main idea for now is to find a good dataset with an interesting biological question/problem to analyze.

**Comment by wdurnoUBC** [comment]
Hey @IssamLaradji , if you feel your problem is solved, please close this thread.

**Comment by IssamLaradji** [comment]
Thanks for the help! I will close this issue now :).
