### ISSUE TITLE
Group project: initial information

### ISSUE THREAD

**Issue by gcohenfr** [STAT540-UBC/Discussion#22]
Post here your initial project proposal, including group memberships and a paragraph describing your project. One per group, due Monday February 2 (or sooner if you are ready). Jenny will create one private repository for each group to host all your project work and interact with your group members.

**Comment by tshalev** [comment]
Differential expression in stone cells from pest-susceptible versus resistant Sitka spruce

Group members:
Judith Booth
Ivan Hartling 
Dan Kehila
Evan Cronmiller
Tal Shalev

The white pine weevil (WPW) is a forest insect pest that affects conifer species throughout North America and Sitka spruce in particular in Northwestern coastal rainforests. WPW adults feed on the inner bark (cortex) of the previous year’s apical shoot tip where they oviposit in early spring. Larvae feed downwards inside of the shoot, girdling the phloem and eventually the xylem destroying one or more years of apical shoot growth. Repeated attacks lead to stunted growth and death of the tree. High density of stone cells in the bark of some genotypes of Sitka spruce has been associated with a rare genetic resistance against WPW. Laser micro dissection (LMD) was used to excise developing stone cells from both resistant and susceptible genotypes and RNA-Seq was performed. We wish to assess whether differential expression in occurring between different tissues. We will perform statistical tests for significant difference of the levels of transcripts for candidate genes that will be identified in BLAST searches. The Limma package will be used in R to calculate fold-change and to test which genes have significantly different levels of transcripts between samples. Graphics packages such as ggplot2 or lattice will be used produce heatmaps and other graphics.

**Comment by santina** [comment]
### Identifying aberrant methylation patterns underlying colorectal cancer progression
----------------

#### Group Members

Member	| Graduate Program |	Lab Group | Interest/Expertise |
------------- | -------------|------------- |------------- |
Rashedul Islam @Rashedul	|Bioinformatics Training Program| Dr. Martin Hirst (CHiBi) | *De novo* Sequence Assembly, Genetics and Molecular Biology, RNA-seq and ChIP-seq Data  Analysis |
Santina Lin @Santina  |Bioinformatics Training Program| Dr. Steven Jones (BCGSC) | Data Visualization, Data Analysis, Data Mining  |	
Ka Ming Nip @kmnip	|Bioinformatics| Dr. Inanc Birol (BCGSC) | Data Visualization, Sequence Assembly, Structural Variation Analyses, Pathogenomics|
Eva Yap	@evayap|Experimental Medicine|	Dr. Aly Karsan (BCGSC) | Biochemistry |
Beryl Zhuang @BerylZhuang	|Bioinformatics Training Program| Dr. William Hsiao (BCCDC) | Genetics, Application of Bioinformatics tools |	
- CHiBi = Centre for High-Throughput Biology
- BCGSC = Canada's Michael Smith Genome Sciences Centre		
- BCCDC = BC Centre for Disease Control

#### Project proposal

Colorectal cancer (CRC) step-wise progression is associated with the accumulation of aberrant DNA methylation. This includes hypermethylation of CpG islands which are sequences with high CpG fraction (>50%) located within gene promoters resulting in transcriptional silencing of tumour suppressor genes **(1,2)**. Changes in DNA methylation is one of the early molecular events involved in CRC progression and many studies have identified these epigenetic abnormalities in precursor lesions such as aberrant crypt foci and adenomas **(3,4,5)**. Methylation aberrations can also mediate field defect, a phenomenon in which histologically normal tissues are predisposed to malignant transformation due to the presence of molecular alterations **(6)**. In this project, we aim to compare DNA methylation patterns (specifically hypermethylation of CpG islands) between normal tissues, colon adenomas, and colorectal tumours as well as comparison of tumours with paired normal tissues from CRC patients. To achieve this, we will analyze DNA methylation array data from [GSE48684](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48684) generated by the Illumina HumanMethylation450 BeadChip platform [GPL13534](http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL13534), which is publicly available on the Gene Expression Omnibus (GEO). This dataset consists of four sample groups, namely normal intestinal tissues from non-CRC patients (n = 17), normal intestinal tissues from CRC patients (n = 24), colon adenomas (n = 42), and colorectal tumours (n = 64). Identifying specific DNA methylation markers underlying CRC progression could be translated into a clinically applicable tool to improve early detection, risk assessment, disease monitoring, and therapeutic intervention of CRC.

#### References

1. Li, J. et al. ISRN Gastroenterol. 2014 Mar 6; 2014:464015.
2. Vaiopoulos, A. G. et al. Biochim. Biophys. Acta. 2014 Feb 20; 1842(7):971–80.
3. Luo, Y. et al. Gastroenterol. 2014 Apr 23; 147(2):418–29.e8.
4. Chan, A. et al. Am. J. Pathol. 2002 Jan 24; 160(5):1823–30.
5. Muto, Y. et al. BMC Cancer. 2014 Jun 25; 14:466.
6. Shen, L. et al. J. Natl. Cancer Inst. 2005 Sept 21; 97(18):1330–8.

**Comment by santina** [comment]
We already set up a  [Github repository for our group](https://github.com/santina/CrystalMethylation). Since it already has a lot of content and discussion, could we just use this one please?

**Comment by aliceZhu** [comment]
@santina I think your group's readme file and the embedded links have all the content we are looking for in this proposal, @gcohenfr Gaby, do you think it's fine for Santina's group to use that instead for this proposal?

However, Jenny and Gaby will create a private repository for your group for the future works regarding the project.

**Comment by santina** [comment]
I meant since we already have a lot of content, progress, and discussion on our current repo I was wondering if we could just use that one instead of starting all over again with a new repo? Is it mandatory that our work has to be on a private repo created by the instructors?

**Comment by yyolanda** [comment]
### Asthma inhalation challenge study
***
#### Group Members
| Member | Introduction |
|---|---|
| Max Alander | Max Alander is a Biomedical Engineer student in Sweden and is currently on exchange at UBC. He is technically done with his undergrad in Sweden but he hasn't really chosen a field for the graduate here at UBC or back in Sweden. Some of his fields of interest are signal processing and health monitoring devices. |
| Yolanda Yang | Yolanda Yang is first year master student in the Experimental Medicine program working with Dr. Scott Tebbutt at Center for Heart + Lung Innovation and Dr. Ed Conway at Center for Blood Research. Her current research project is to look at the effect of complement system-related genes/proteins on the late phase response of allergic asthma. |
| Naman Paul | Naman Paul holds an engineering degree in Bioinformatics. Currently, a Master's student in the Bioinformatics program working with Dr. Art Cherkasov at the Vancouver Prostate Centre. He is working in the in-silico Drug Discovery lab, with special focus on chemo-informatics and 4D QSAR prediction for cancer agonists/antagonists. |
| Akiff Manji | Akiff Manji has a background in Cell Biology and Genetics and Computer Science. He has previous laboratory experience in Molecular Biology and is currently working on a web-based whole genome analysis platform with the Laboratory for Food Borne Zoonoses at the Public Health Agency of Canada. |
| Basia Rogula | Basia Rogula is a first year student enrolled in the MSc in Statistics program at UBC. Before commencing graduate studies, Basia worked at the Centre for Clinical Epidemiology and Evaluation. There she ran the analysis for a series of studies, mostly involving waiting times data for coronary artery bypass surgery. |
| Hamza Khan | Hamza Khan is a first year master student in the Bioinformatics Graduate program at UBC. He is currently working on a rotation project under Dr.Fiona Brinkman at Simon Fraser University. His fields of interest include constructing 'next generation sequencing data' analyses pipelines, its acceleration and optimization. |
***
#### Project Introduction
Asthma is a chronic inflammatory disorder of the airways characterized by airway hyperresponsiveness and reversible airflow obstrction. Symptoms include recurrent episodes of wheezing, breathlessness, chest tightness and coughing (WBCC), particularly at night or early morning. Both an early response and a late response is involved in allergic asthma. Individuals will experience acute bronchoconstriction (a drop in FEV1 (forced expiratory volume in 1 second)) upon allergen exposure. This is known as the early response and the FEV1 will typically go back to normal in 2 hours. However, some individuals will also experience another chronic bronchoconstriction (a drop of 20% in FEV1) after several hours of the initial exposure whereas others do not. This chronic late phase can last as long as several days and is known as the late response. An individual with only the early response is classified as an early responder (ER) while an individual with both the early response and the late response is classified as a dual responder (DR). Investigating transcriptomics in whole blood is a promising avenue of research for helping to understand the allergic response [1-3]. Knowing how gene expression changes during an allergic response is important to discover new therapeutic targets and improve diagnosis. In addition, since fatal or severe asthma always develops among the DRs, it is essential to understand the different pathways leading to two phenotypes for prevention of development. Therefore, in this project it is hoped that we can discover novel biomarkers and/or targets that can be used for asthma diagnosis and treatment. We are going to use a microarray dataset which contains the gene expression in whole blood of 14 mild asthmatics. The subjects went through an cat-allergen inhalation challenge and their blood samples were collected before and 2 hours after the challenge. Of the 14 subjects, 8 subjects are classified as ERs and 6 subjects are classified as DRs according to the above rubric. Expression profiling was performed using Affymetrix Human Gene 1.0 ST arrays. The dataset has 28 samples and approximately 22,000 probesets. 
***
#### Reference
- Chaussabel, D., Pascual, V., & Banchereau, J. (2010). Assessing the human immune system through blood transcriptomics. _BMC Biology, 8,_ 84-7007-8-84.
- Kam, S. H., Singh, A., He, J. Q., Ruan, J., Gauvreau, G. M., O'Byrne, P. M., . . . Tebbutt, S. J. (2012). Peripheral blood gene expression changes during allergen inhalation challenge in atopic asthmatic individuals. _The Journal of Asthma : Official Journal of the Association for the Care of Asthma, 49(3),_ 219-226.
- Singh, A., Yamamoto, M., Kam, S. H., Ruan, J., Gauvreau, G. M., O'Byrne, P. M., . . . Tebbutt, S. J. (2013). Gene-metabolite expression in blood can discriminate allergen-induced isolated early from dual asthmatic responses. _PloS One, 8(7),_ e67907.

**Comment by mas29** [comment]
Group members: 

Maia Smith 
•  MSc. Bioinformatics
Ben Callaghan
•	MSc. GSAT
Matthew Bundala
•	MSc. GSAT
Daniel Dinsdale
•	PhD. Statistics
Jack Ni
•	MSc. Statistics


Project Proposal:

Our objective is to determine which mechanisms of cell death are elicited by different small molecules. Whether or not similar compounds elicit different mechanisms of cell death will be determined. To accomplish this, we are exploring the relationship between properties of cell death and the properties of small molecules. 

Our data consist of time series images from the IncuCyte system. Each well in the IncuCyte machine has muscle cells, treated with tunicamycin, sytox green and one variable compound. The variable compound is drawn from 1833 compounds. Sytox green is a fluorescent nuclear stain, and is taken up by the cells as they die. In addition to the raw images, the IncuCyte system counts how many cells in each well have taken up the fluorescence, and outputs this measure at 2 hour intervals for 48 hours. Thus, our dataset consists of fluorescence curves describing the death of muscle cells in response to the variable compound.  

We intend to look at the data through two major lenses. Firstly, we plan to use features of the curves to discover compound groups that may elicit cell death through similar mechanisms. Secondly, we plan to use features of compounds themselves (provided cheminformatic data) to group curves. We may thereafter compare the clustering of curves and compounds between the different methods. 

This analysis is purely exploratory, and will involve clustering and data visualization. We will explore various ways to cluster and compare curves.

**Comment by swils6** [comment]
Members:
Samantha Wilson-   PhD; Medical Genetics,Dr. Wendy Robinson: Epigenetics/ DNA methylation
Chaini Konwar-	PhD; Medical Genetics,Dr. Wendy Robinson: Epigenetics/DNA methylation
Lisa McEwen -        MSc: Medical Genetics,Dr. Michael Kobor: Epigenetics/DNA methylation
Bradley Balaton-     MSc: Medical Genetics, Dr. Carolyn Brown: X chromosome inactivation
Tanja Hoegg-         PhD: Statistics,TBA: Statistical Analysis; Previously breast cancer risk assessment

Title: Characterization of placental DNA methylation profiles from pregnancies complicated by preeclampsia and/or intrauterine growth restriction.

Background
Placental insufficiency occurs when the placenta is unable to provide an adequate supply of nutrients to the growing fetus, which can lead to a number of complications including intrauterine growth restriction (IUGR). IUGR often occurs conjunctively with preeclampsia (PE), a maternal multi-system hypertensive disorder which manifests as a result of maternal hypertension and proteinuria after 20 weeks (wks) gestation. Early-onset PE (EOPE) arising prior to 34wks gestation tends to be more severe and is associated with greater placental changes and with greater frequency of IUGR as compared to late-onset preeclampsia (LOPE), arising after 34wks. Babies from pregnancies complicated by PE and/or IUGR are at an increased risk for intrauterine fetal demise and preterm birth; additionally, PE is one of the leading causes of maternal and perinatal morbidity and mortality worldwide. Currently, there is no consistent method to identify women at high risk of developing these complications, and management mainly revolves around prolonging gestation to maximize fetal health outcomes, while managing maternal symptoms. Early detection of PE and IUGR before clinical signs of disease is important for improved management and outcomes of affected pregnancies.
	PE and IUGR are both thought to arise due to placental trophoblast cells failing to invade the maternal uterine wall and remodel the maternal vasculature, resulting in decreased blood flow and hypoxic conditions for the fetus. However, it is unclear how these conditions, with very different phenotypes can arise due to the same cause. Despite much research in field, the exact pathogenesis of PE and IUGR and the heterogeneity between them, remains relatively unclear. We propose to investigate DNA methylation (DNAm), a chemical addition to DNA, that influence how genes are expressed, to characterize the epigenetic profile of placentas from pregnancies complicated by PE and IUGR. DNAm profiling will help establish whether there are commonalities in placental pathology underlying PE-associated IUGR compared to normotensive IUGR, and help define the heterogeneity between these complications and their subtypes.

Hypothesis
We hypothesize IUGR and PE have distinct etiologies associated with unique epigenetic profiles. Additionally, we expect that clinical parameters such as: gestational age, fetal sex, birth weight, and placental dimensions, will influence DNAm, and will need to be modeled within our statistical analyses.

Plan
1.	Measure DNAm using the Illumina HumanMethylation450 array
2.	We will first normalize and preprocess our data, correcting for batch effects, removing the XY chromosome probes to minimize sex effect, removing probes with known SNPs in the CpG of interest, and removing non-specific probes and probes that cross hybridize to the sex chromosomes. Additionally, we will also remove samples that have bad detection p values or missing beta values.
3.	Investigate the association of differential DNAm with clinical parameters such as: gestational age, fetal sex, birth weight, placental weight, placental dimensions etc.
4.	Characterize the DNAm profiles of EOPE, LOPE, nIUGR and control placentae. Additionally, we aim to assess a possible interaction between PE and IUGR in pregnancies complicated by both conditions.

Samples
Cases are divided into three groups: EOPE (N=21), LOPE (N=19), and normotensive IUGR (N=12). We have excluded samples based on i) chromosomal abnormalities, ii) pregnancies complicated by gestational diabetes, iii) chorioamnitis, iv) essential hypertension, and v) multi-fetal pregnancies. 
PE is defined according to Society of Obstetricians and Gynecologists of Canada (SOGC) criteria as one of i) hypertension (BP>140/90mm Hg) and proteinuria (>300g/day) arising after 20 weeks gestation; ii) HELLP syndrome without hypertension or proteinuria; or iii) eclamptic seizure without previous hypertension or proteinuria. EOPE is defined by a diagnosis of PE prior to 34wks gestation, and LOPE is defined as a diagnosis after 34wks gestation. IUGR is also defined following SOGC criteria as birth weight < 3rd percentile accounting for fetal sex and gestational age, or birth weight< 10th percentile with additional clinical findings indicative of poor growth. 

References and related works
1. Steegers, E. A., von Dadelszen, P., Duvekot, J. J. & Pijnenborg, R. Pre-eclampsia. The Lancet 376, 631-644 (2010).
2. Suhag, A. & Berghella, V. Intrauterine Growth Restriction (IUGR): Etiology and Diagnosis. Current Obstetrics and Gynecology Reports 2, 102-111 (2013).
3. Sankaran, S. & Kyle, P. M. Aetiology and pathogenesis of IUGR. Best Practice & Research Clinical Obstetrics & Gynaecology 23, 765-777 (2009).
4. Blair, J. D. et al. Widespread DNA hypomethylation at gene enhancer regions in placentas associated with early-onset preeclampsia. Mol. Hum. Reprod. (2013).

**Comment by wongoli** [comment]
**Exploring the relationship between histone variant H2A.Z and non-coding RNA in Saccharomyces cerevisiae.**

**Full members:** 
**Sachini Ariyaratne** - Department of Biochemistry (Dr. Michael Kobor). Interests: Chromatin/Histone variants/Histone modifications
**Derek Chiu** – Department of Statistics, MSc. In Biostatistics. Interests: Data aggregation, visualization, analysis, and modelling
**Madeline Couse** – Genome Science and Technology (Rotations). Interests: TBD
**Veronique LeBlanc** – Genome Sciences and Technology (Dr. Marco Marra). Interests: Epigenetic modifications in low-grade gliomas
**Alison McAfee** – Genome Sciences and Technology (Dr. Leonard Foster). Interests: Host-pathogen interactions in honey bees
**Olivia Wong** – Department of Biochemistry (Dr. Michael Kobor). Interests: Chromatin remodeling and histone modifications. 

**Additional members (auditing students):**
**Frank Ye** - Genome Sciences and Technology (Dr. Peter Stirling)

**Brief description of project:** 
In eukaryotes, DNA is packaged by wrapping the molecule around a histone octamer to form nucleosomes, which can then be further packaged into chromatin. The histone octamer is normally composed of histones H2A, H2B, H3 and H4; however, canonical histones can also be replaced with histone variants such as H2A.Z. Though the functional significance of H2A.Z deposition remains poorly understood, studies have shown that H2A.Z enrichment in nucleosomes flanking the 5’ end of protein-coding genes can have both activating and repressive effects in S. cerevisiae. Here, we will investigate whether H2A.Z deposition plays a role in the generation of non-coding RNA (ncRNA) and whether the latter can regulate gene expression. In vivo, ncRNAs are normally unstable and readily degraded; however, inducing a mutation in the RNA surveillance protein Rrp6 can lead to increased ncRNA stability and abundance. We will use a recently published dataset (GSE54105) which includes chromatin immunoprecipitation sequencing (ChIP-Seq) data, to probe H2A.Z deposition, as well as transcriptome sequencing (RNA-Seq) to measure ncRNA and protein-coding gene expression in Rrp6∆ and wild-type yeast strains. First, we will identify transcriptional start sites (TSSs) of ncRNAs and relate this to the loci of H2A.Z deposition as indicated by ChIP-Seq. If ncRNA expression cannot be explained by H2A.Z deposition alone, we will use an additional data set (GSE52000) to investigate ncRNAs’ correlation with other activating and silencing histone marks. Next, we will examine the impact of increased ncRNA abundance on protein-coding gene expression in the absence of Rrp6 expression. Overall, we anticipate that this analysis will provide some insight into the role of histone modifications in ncRNA-regulated gene expression.

**Comment by tshalev** [comment]
## Differential expression in stone cells from pest-susceptible versus resistant Sitka spruce
Group members | Graduate Program | Lab | Interests/Expertise
--------------------|------------------------|------|-----------------------
Judith Booth | Genome Science and Technology | Dr. Jörg Bohlmann | Role of genetics in plant metabolism and the role of metabolites in flavour and aroma, focusing on terpene production in *Cannabis sativa*.
Evan Cronmiller | Botany | Dr. Jae-Hyeok Lee | Plant Biochemistry, biofuel engineering and GMOs, focusing on *Chlamydomonas* algae
Ivan Hartling | Applied Animal Biology | Dr. Ronaldo Cerri | Vitamins and metabolites in dairy
Dan Kehila | Genome Science and Technology | Rotation | Microbial and viral ecology, proteins and developmental biology
Tal Shalev | Genome Science and Technology | Rotation | Genomics of conifer/insect interactions
---------------------------------------------------------------------------------------------------------------------------------
### Project brief:

The white pine weevil (WPW) is a forest insect pest that affects conifer species throughout North America and Sitka spruce in particular in Northwestern coastal rainforests. WPW adults feed on the inner bark (cortex) of the previous year’s apical shoot tip where they oviposit in early spring. Larvae feed downwards inside of the shoot, girdling the phloem and eventually the xylem destroying one or more years of apical shoot growth. Repeated attacks lead to stunted growth and death of the tree. High density of stone cells in the bark of some genotypes of Sitka spruce has been associated with a rare genetic resistance against WPW. Laser micro dissection (LMD) was used to excise developing stone cells from both resistant and susceptible genotypes and RNA-Seq was performed. We wish to assess whether differential expression in occurring between different tissues. We will perform statistical tests for significant difference of the levels of transcripts for candidate genes that will be identified in BLAST searches. The Limma package will be used in R to calculate fold-change and to test which genes have significantly different levels of transcripts between samples. Graphics packages such as ggplot2 or lattice will be used produce heatmaps and other graphics.

-----------------------------------------------------------------------------------------------------------
### References:
* Alfaro, R. I., Borden, J. H., King, J. N., Tomlin, E. S., McIntosh, R. L. & Bohlmann, J. (2002). Mechanisms of resistance in conifers against shoot infesting insects. In M. R. Wagner, K. M. Clancy, F. Lieutier, & T. D. Paine (Eds.), Mechanisms and deployment of resistance in trees to insects (pp. 105-130). Dordrecht: Springer Netherlands.
* Franceschi, V. R., Krokene, P., Christiansen, E. & Krekling, T. (2005). Anatomical and chemical defenses of conifer bark against bark beetles and other pests. New Phytol., 167, 353-376.
* King, J. N., Alfaro, R. I., Lopez, M. G. & Van Akker, L. (2011). Resistance of Sitka spruce (Picea sitchensis (Bong.) Carr.) to white pine weevil (Pissodes strobi Peck): characterizing the bark defence mechanisms of resistant populations. Forestry, 84, 83-91.
* Wang, H. Z. & Dixon, R. A. (2012). On-Off Switches for Secondary Cell Wall Biosynthesis. Mol. Plant, 5, 297-303.

**Comment by IssamLaradji** [comment]
| Member| Program| Lab| Interest/Expertise|
|:----------------------------|:-------------|:-----|:------|
| Leonie Bauer      | B.Sc. Biology, 3rd year (visiting student at UBC) | - |Cognitive Neurosciences, Neurobiology |
| Chris Cameron     |M.Sc. Computer Science, 1st year      |   BETA Lab (Bioinformatics,Empirical, and Theoretical Algorithms) | Machine Learning, Empirical Algorithms, Bioinformatics, Software Development |
| Issam H. Laradji |M.Sc. Computer Science, 1st year      |    - |Machine Learning, Optimization theory |
| Rebeca Cardim | M.Sc. Applied Mathematics      |    IAM (Institute of Applied Mathematics) | Signaling, Single Particle Tracking |
| Catherine Byrne | M.Sc. Applied Mathematics      |   - | Viral dynamics and cancer immunology modeling |

Project Proposal
----------------------

**Exploring the effect of cytokines on gene expression of  CD4+ T cells**

Understanding how differences among individuals affect the way immune cells respond to different types of stimulants is vital for developing effective, personalized vaccines and treatments to patients. We propose to investigate variations in RNA expression before and after T cell stimulation through statistical evaluation of two datasets: (1) a baseline dataset [1] containing 21765 CD4+ T cell’s gene expressions from 499 individuals; and (2) a response dataset [2], corresponding to ~300 participants in the baseline, that represent 250 CD4+ T cell’s gene expressions after being stimulated. CD4+T cells are crucial in the regulation of immune responses in that they activate other immune cells through the secretion of specific cytokines. Naive CD4+T cells are activated after interaction with antigen-MHC complexes, and differentiate into distinct T cell subtypes depending mainly on the cytokine milieu of the microenvironment [3]. Using beads coated with anti-CD3 and CD22, the T-cells were stimulated in three ways: without cytokines (unbiased activation), with IFN-β cytokines, and with Th17 cytokines. Cytokines are proteins secreted by host leukocytes and some non-immune cells in response to pathogen infections. They elicit a wide variety of cell responses, ranging from activation of components of the adaptive and innate immune responses and direct action on infected cells. IFN-β belong to interferons, a family of cytokines produced in response to viral infections. Th17 cytokines are produced by Th17 cells and play an important role in inflammatory processes [4]. Ye et al. [5] show that cytokines lead to changes in gene expressions of T cells based on interindividual variability. The authors suggest that T cells are activated differently for distinct individuals based on variables such as gender, age and ethnicity. We will explore the relationship between T cell responses among different individuals by testing whether there is significant differences between RNA expression levels in response to different stimulants. We will also test whether it is feasible to infer T-cell activation in response to the different stimulants and infer cytokine stimulation from T cell activation data. Specifically, we propose to test the hypothesis that T cell gene expressions from stimulated T cells differ from those of resting T cells and evaluate whether gene expression of T cells stimulated with IFN-β and those stimulated with Th17 are significantly different. To perform inference, we first plan to apply canonical correlation analysis (a general case of principal component analysis) to determine latent variables from baseline gene expressions and metadata variables (such as gender, age and ethnicity) that best correlate the baseline with the response gene expressions. Using these latent variables, we will build a set of linear (or non-linear) models to predict the effects of cytokines on individual gene expression values.

References
---------------
[1] Immune Variation Project (ImmVar) [CD4]      (“http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE56033 “)

[2] Expression data measured by custom Nanostring gene set of CD4+ T cells from healthy individuals stimulated with anti-CD3/CD28 with or without IFNb or Th17 polarizing cytokines.
(http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60341)

[3] Luckheeram, R. et al. “CD4+T Cells: Differentiation and Functions.” Clinical and Developmental Immunology (2012). doi: 10.1155/2012/925135

[4] Jadidi‐Niaragh, F., and A. Mirshafiey. "Th17 cell, the new player of neuroinflammatory process in multiple sclerosis." Scandinavian journal of immunology 74.1 (2011): 1-13.

[5] Ye, Chun Jimmie, et al. "Intersection of population variation and autoimmunity genetics in human T cell activation." science 345.6202 (2014): 1254665.

**Comment by jtopham** [comment]
**Pan-Cancer Meta-analysis of mRNA Expression Data**
Different types of cancer have been found to vary wildly in many disease parameters such as aggression, anatomical location, gene mutations, and more. Upon findings like these, initiatives such as personalized medicine have been launched to treat cancer on a per-patient basis. This endeavour has generated a wealth of data in publicly available databases, encouraging cohesive meta-analyses to take advantage of what is coined "big data". However, one common challenge is extracting meaningful biological inferences from such large and complex genetic data. Our cohort has decided to source mRNA-sequence information from The Cancer Genome Atlas (TCGA) compendium due to its rich pan-cancer genome database and comprehensive metadata. We propose to investigate the following hypothesis: pan-cancer trends in mRNA expression correlate with some phenotypic traits. In particular, we will apply statistical clustering methods to group different types of cancer by mRNA expression patterns, followed by analysis of underlying phenotypic traits (such as age, gender, ethnicity, years as a smoker, etc.) The project will be grounded upon two main phases:
1.        Several independent within type analyses, where we will examine mRNA expression patterns independently in several different cancer types. Each group member will perform an analysis of this type on a different cancer.
2.        A between type meta-analysis of the results of the above cancer types, where mRNA expression data will be used to cluster different types of tumors based on similar patterns and underlying phenotypic traits will be analyzed.
The impact of a study such as this is an increase in our knowledge of how different environmental factors can influence mRNA expression patterns and, in turn, how these expression patterns relate to different forms of oncogenesis.
 
**Reference**
 
Ley et al., 2013. *Genomic and epigenomic landscapes of adult de novo acute myeloid leukemia.* N Engl J Med, 368(22):2059-2074
 
**Members**
 
**Connor Morgan-Lang**
Current Program: Bioinformatics Training Program, Hallam lab
Academic Background: BSc. Biology
Research interests: microbial ecology and metagenomics
**James Topham**
Current Program: Bioinformatics Training Program, Marra lab rotation student
Academic Background: BSc. Biology
Interests: NGS analysis
**Dmitrii Tebaikin**
Current Program: Bioinformatics Training Program, Pavlidis lab
Academic Background: BSc Computer Science & Biology
Interests: Text mining
**Mike Gottleib**
Current Program: Bioinformatics Training Program, Karsan lab rotation student
Academic Background: BA Asian Studies & Psychology
Interests: Beer, Bikes & Bioinformatics (BBB)
**Rosemary McCloskey**
Current Program: Bioinformatics Training Program, Mostafavi lab rotation student
Academic Background: BSc. Mathematics
Interests: HIV epidemiology
