### ISSUE TITLE
Assignment 2 Q4.1

### ISSUE THREAD

**Issue by maggie-fu** [STAT540-UBC/Discussion#251]
For the first part of the question, we are asked to retain genes that "have CPM > 1 in *at least as many samples as the smallest group size* ", which implies a greater than or equal to relationship. However, I assumed this step is performed to prevent a group from having all low CPM? In that case, shouldn't the instruction be "have CPM >1 in more samples than the smallest group size"?

**Comment by smaslova** [comment]
I think we're just trying to remove lowly-expressed genes in general because they are more likely to introduce false positives.  But we want to retain any gene that is expressed in all samples of one group but not in any other samples since that would be of actual biological interest.  Therefore, if a gene is expressed in the "smallest group size" of samples, we keep it.  

At least that was my interpretation!

**Comment by maggie-fu** [comment]
It makes sense. Thanks!
