### ISSUE TITLE
Still looking for the 4th group member

### ISSUE THREAD

**Issue by wenzhengzzz** [STAT540-UBC/Discussion#278]
Hi, 
This is Poppy @wenzhengzzz. My expertise is related to behavioural modelling in credit risk management. Along with Cathy @qiaoyuet, she's focusing on classification on imbalanced clinical data. We are master students in statistics with experience in R. We are looking for 2 more group members with other backgrounds and we are open for the project topics (depends on your background).  If you are interested, please leave a message.

Poppy&Cathy

**Comment by vpichler** [comment]
Hi Poppy and Cathy, 

My name is Ginny (@vpichler) and I am a first year PhD student studying infectious disease genomics in the Department of Microbiology and Immunology, with a biology background from both my undergrad and masters. Since my forte is biology. I have not yet generated data in my research, so I'm flexible to pull public data or jump on any you have in mind.

Anthony (@antjak) is an exchange student from Switzerland (EPFL) studying Biomedical Engineering, with a background in biology (courses and lab experience) and machine learning (also taking CPSC 540, a machine learning course, this term). 

Anthony and I have formed a pair and were looking for stats team members. 

Feel free to shoot me an e-mail too (virginia.pichler@bccdc.ca)

  Ginny

**Comment by wenzhengzzz** [comment]
Hi Ginny @vpichler & Anthony, 

Sounds great! We are a team now! Please let me know which way you feel most comfortable to discuss our group project. My email is wenzheng.zhou@stat.ubc.ca for your reference.

Poppy

**Comment by vpichler** [comment]
Hi Poppy,


I received a reply back from another stats pair literally one minute before your e-mail came in and I've already confirmed with them.


Thanks for getting back and good luck in team member hunt!


  Ginny

________________________________

**Comment by wenzhengzzz** [comment]
@vpichler  no worries. Good luck in your project

**Comment by wenzhengzzz** [comment]
@gkeais Graeme just joined us, so we are seeking for the 4th group member now! Graeme is a first-year Ph.D. student in the Botany with a BSc and an MSc in Biology, studying the genomics of sunflower. His previous work has focused primarily on evolution and genetics.
