### ISSUE TITLE
Looking for final team member

### ISSUE THREAD

**Issue by jwhite94** [STAT540-UBC/Discussion#282]
Hello STAT540 friends,

@anthonyopped @jokagyeman and I have formed the team _Statistically Magnificent_ and plan to work with a data set containing SNP frequency in a Tunisian population with/without Parkinson's Disease (provided by @anthonyopped). Anthony and I are both in the Medical Genetics program while Jonathan is studying Statistics. To ensure we have a diverse set of backgrounds, we are hoping to find someone with a computer science focus or at the very least, a non-biology skillset.

Leave a comment if you are interested in joining!

**Comment by ppavlidis** [comment]
Hi Justin, probably we're not going to have more than one stats student per team. We've already had to do some "manual distribution", so be prepared for that possibility.

But I mostly came over here to comment on the data set. Often this kind of SNP data has not worked out very well for group projects. If you have SNP frequency data in two populations, that's an N of 1 per group ... hopefully that's not what you mean, and you have individual-level data. But even then, since we don't cover SNP analysis in a lot of detail in the course, it may be harder for us to support you, depending on the data and the plan. Feel free to ask for more input, no need to wait for the formal deadline for initial project submission.

**Comment by jwhite94** [comment]
Hi Dr. Pavlidis,

Sorry I should have specified that we do have individual-level data. Also, there may be transcript data available as well so that may be better to use if you believe SNP analysis may be a challenge.

Thank you for the warning regarding more than one STAT student per team, we will try to recruit someone with a different program.

To everyone else, we are still searching for a fourth member so let us know if you might be interested!

**Comment by ppavlidis** [comment]
Definitely having transcriptome data in addition to genotypes would open up a lot of possibilities that are in line with course content, thanks for clarifying.

**Comment by parashloya** [comment]
Hello @jwhite94, I am Parash from biology background especially, genetics and bioinformatics. If you are still looking for fourth member, I am interested.
Please let me know.

**Comment by parashloya** [comment]
I have done few courses on bioinformatics in my undergradatuation.
And I will be happy to be part of your group.
