### ISSUE TITLE
Deadlines & participation points regarding the seminars

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#32]
Since there are no official deadlines nor a clear grading scheme for the seminars, it becomes easy to forget about doing them when you get caught up with other course work, like homeworks, projects and exams. 

While the seminars count towards participation points, it would be great if deadlines were set (maybe two weeks or three weeks after the take-home problems are released), so that we arrange a time to work on them. Also, some overview as to how participation points are lost would be great.

The goal of this suggestion is to know the number of days the seminar submission can be delayed before losing any **participation points**, which make up a good portion of the **final grade**. 

Thanks!

**Comment by jennybc** [comment]
I agree with this request to set some expiration date on the seminars. Last year we had some understandable-but-unproductive behaviour, where students did work on the seminars very very late in the course. The whole point is that work on the seminars will make the homework and project __immensely__ easier. It will surface misunderstandings early enough to take advantage of the TAs and profs and get questions answered. The main reason to award some credit for it is to motivate people to engage with the content in a low stakes way, on a regular basis.

It actually makes marking easier because TAs can note the state of the repos w/r/t each seminar as the semester progresses, instead of doing all of that at the end.

That's my two cents as course head prior to 2015,
