### ISSUE TITLE
Any insight into crazy limma-voom output?

### ISSUE THREAD

**Issue by tfsevers88** [STAT540-UBC/Discussion#335]
This is the output we're getting with limma-voom with our count data. Any ideas about what might cause the curious curve on the left? Shams and Will hadn't seen anything like it before. I've tried adding a number of parameters from clinical data to our model that were excluded from the model used in the published paper, but the curve persists. 

![image](https://user-images.githubusercontent.com/13499473/55122291-9fb42300-50bb-11e9-97a5-f5173fb392af.png)

**Comment by ppavlidis** [comment]
This is what happens when you don't filter for lowly expressed genes first, as discussed in lecture.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: tfsevers88 <notifications@github.com> Date: 2019-03-27  18:21  (GMT-08:00) To: STAT540-UBC/Discussion <Discussion@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [STAT540-UBC/Discussion] Any insight into crazy limma-voom output? (#335) This is the output we're getting with limma-voom with our count data. Any ideas about what might cause the curious curve on the left? Shams and Will hadn't seen anything like it before. I've tried adding a number of parameters from clinical data to our model that were excluded from the model used in the published paper, but the curve persists.


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/STAT540-UBC/Discussion","title":"STAT540-UBC/Discussion","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/STAT540-UBC/Discussion"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Any insight into crazy limma-voom output? (#335)"}],"action":{"name":"View Issue","url":"https://github.com/STAT540-UBC/Discussion/issues/335"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/STAT540-UBC/Discussion/issues/335",
"url": "https://github.com/STAT540-UBC/Discussion/issues/335",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tfsevers88** [comment]
Hmmm... I did, but maybe not stringent enough since this was counts rather than cpm?

`filteredCounts <- filteredCounts[rowSums(filteredCounts > 1) >= smallestGrp,]`

**Comment by ppavlidis** [comment]
Yes, that's not stringent enough in general. I don't know what smallestGrp is, but you will end up with genes that have almost no data. That is never reliable -- some guidelines suggest reliability of diff. ex. is poor genes in the lowest 1/3 of expression levels.
