### ISSUE TITLE
Initial proposal due Thursday Jan 23rd

### ISSUE THREAD

**Issue by wvictor14** [STAT540-UBC/Discussion#346]
Hi all, 

It's time to make your **initial project proposals** and **pick a team name**!

Copy everything below the horizontal line, paste it into your comment, and fill out the information. Just one comment per team.

```
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| example: Victor Yuan | Genome Science and Technology |  Epigenetics, Bioinformatics |  @wvictor14|
| Sina jafarzadeh | Bioinformatics  |  Molecular Evolution | @jafarzadeh91 |
|  |   |  |
|  |   |  |

Team name: 

One paragraph on the basic idea of the project: 
```

------------------------

The output would look like this:

| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| example: Victor Yuan | Genome Science and Technology |  Epigenetics, Bioinformatics |  @wvictor14|
| Sina jafarzadeh | Bioinformatics  |  Molecular Evolution | @jafarzadeh91 |
|  |   |  |
|  |   |  |

Team name:  5mC's on an island

One paragraph on the basic idea of the project and the dataset:

**Comment by mksm1228** [comment]
Hi, do we make our own group repository or will you be making them for us?

**Comment by sciclic** [comment]
| Name | Department/Program | Expertise/Interests | GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Nikita Telkar | Medical Genetics |  Gene expression, ancestry, and quesadillas  |  @nikita-telkar |
| Sierra Gillis | Genome Science and Technology  |  Cancer phylogenetics, single-cell genomics, and donuts | @gillissierra |
| Naila Adam | Genome Science and Technology | Cancer genomics, ovarian cancer, and caramel macchiato | @naila53 |
| Icíar Fernández Boyano | Genome Science and Technology | Pre-eclampsia, epigenetics, and craft beer | @sciclic |

Team name: The GINNS (**G**roup, **I**cíar, **N**aila, **N**ikita, **S**ierra)

A typical analysis would be to compare differences between two conditions (for example, disease and control). We plan to take this a step further by studying a disease cohort containing methylation and expression data for the same condition, and to investigate the relationship between the two data types. In particular, we will completing this assessment using the datasets [GSE101641](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE101641&fbclid=IwAR33dlTVSPglaE7sRolOqHBNpXy7-V_uwO7RbZLuxta2cdt7b-7jfOFonKo) and [GSE127696](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE127696&fbclid=IwAR1IvJe97C-JZSyqXw_71Btx2XzE10zmaF8rWg8UVf0WMtyfAfxS2HqGCtM), which are publicly available on GEO. These datasets concern the genetic disorder **cystic fibrosis** (CF), a disease that affects mostly the lungs, but also the pancreas, liver, kidneys, and intestine.

**Comment by wvictor14** [comment]
@mksm1228 we will make your group repositories for you based on your team name

**Comment by hauduc** [comment]
| Name | Department/Program | Expertise/Interests | GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Axel Hauduc | Genome Science and Technology |  Cancer & Aging Epigenetics | @hauduc |
| Alex Marr | Genome Science and Technology  |  Yeast Genomics, Industrial Microbiology  | @marralex |
| Fred Sunstrum | Genome Science and Technology | Plant Natural Product Biosynthesis | @fsunstrum |
| Ryan Stubbins | Experimental Medicine | Malignant Hematology | @rstubbins |

Team name: 40 Degrees to Freedom

Acute myeloid leukemia (AML) is an aggressive hematologic malignancy with a generally poor outcome. (1) The genesis of AML lies in the accumulation of both gene mutations and epigenetic dysregulation, particularly with advancing age. (2) Particularly, mutations in epigenetic regulatory proteins (DNA Methyltransferase 3A, DNMT3A; Tet Methylcytosine dioxygenase 2, TET2; Putative Polycomb group protein, ASXL1) are known to be early founding events that establish a background of clonal hematopoiesis upon which synergistic driver mutations occur, producing AML. (2, 3) When these mutations occur in the absence of overt hematologic disease, it is referred to as clonal hematopoiesis of indeterminate potential (CHIP); CHIP is surprisingly common in older individuals, with an estimated prevalence of 10-20% at age ≥ 70 years. (3, 4) While the clinical consequences of isolated CHIP has been characterised (e.g. increased cardiovascular disease risk), the implications of the presence of CHIP-like mutations in AML remains relatively uncharacterised. (5) We propose that the presence of CHIP-like mutations (DNMT3A, TET2, ASXL1) in patients with de novo diagnoses of AML portends a worse prognosis with regards to achievement of complete remission (CR), event-free survival (EFS), and overall-survival (OS), or others, due to a reduced ability to eradicate CHIP-like clones with conventional cytotoxic chemotherapy. We will assess this using a comprehensive AML dataset from The Cancer Genome Atlas (TCGA) which includes annotated data on the presence or absence of known pathogenic mutations in AML, RNA-seq expression data, methylation data, and clinical outcome data. In addition to assessing the influence of the presence of mutations on outcome, we will examine whether mutation type, expression level of mutant allele, and methylation status at specific loci influence prognosis.

1.	Sanz MA, Fenaux P, Tallman MS, Estey EH, Löwenberg B, Naoe T, et al. Management of acute promyelocytic leukemia: updated recommendations from an expert panel of the European LeukemiaNet. Blood. 2019;133(15):1630-43.
2.	Papaemmanuil E, Gerstung M, Bullinger L, Gaidzik VI, Paschka P, Roberts ND, et al. Genomic Classification and Prognosis in Acute Myeloid Leukemia. N Engl J Med. 2016;374(23):2209-21.
3.	Steensma DP. Clinical consequences of clonal hematopoiesis of indeterminate potential. Blood Adv. 2018;2(22):3404-10.
4.	Young AL, Challen GA, Birmann BM, Druley TE. Clonal haematopoiesis harbouring AML-associated mutations is ubiquitous in healthy adults. Nat Commun. 2016;7:12484.
5.	Jaiswal S, Natarajan P, Silver AJ, Gibson CJ, Bick AG, Shvartz E, et al. Clonal Hematopoiesis and Risk of Atherosclerotic Cardiovascular Disease. N Engl J Med. 2017;377(2):111-21.

**Comment by nZhangx** [comment]
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Rachel Miller | Bioinformatics |  Molecular epidemiology | @rachmiller |
| Ishika Luthra | Bioinformatics  | Machine learning and multi-omics dataset  | @IshikaLuthra |
| Yichen Zhang | Statistics  | Statistical methodology, result interpretation, proficient in R coding, visualization | @thisisyichenzhang |
| Nicole (Xi) Zhang | Bioinformatics | Genome regulation, machine learning | @nZhangx |

Team name: CRISPR bacon

Cancer that occurs in the immune cells of the body is commonly referred to as lymphoma. Although lymphoma displays notable genetic heterogeneity, several genetic drivers of the disease have been defined [1].  Our project will aim to characterize differences in gene expression between lymphoma and non-lymphoma patients and describe driver gene expression in lymphoma patients. Our hypothesis is that differences in expression will exist in some genes between lymphoma and non-lymphoma patients, and that some of these genes will be associated with notably strong changes in expression, congruent with driver gene criteria [1]. The rate of overall survival for lymphoma patients is currently 72% [2], meaning that almost a third of lymphoma cases are untreatable using currently known therapies. Exploration of the gene expression landscape has previously provided a successful route to new targets for drug development and refined diagnostic procedures [3-5], suggesting that further characterization of gene expression differences could be similarly beneficial.

[1] Reddy, A., Zhang, J., Davis, N. S., Moffitt, A. B., Love, C. L., Waldrop, A., … Dave, S. S. (2017). Genetic and Functional Drivers of Diffuse Large B Cell Lymphoma. Cell, 171(2), 481-494.e15. https://doi.org/10.1016/j.cell.2017.09.027
[2] Youn, A., Kim, K. I., Rabadan, R., Tycko, B., Shen, Y., & Wang, S. (2018). A pan-cancer analysis of driver gene mutations, DNA methylation and gene expressions reveals that chromatin remodeling is a major mechanism inducing global changes in cancer epigenomes. BMC Medical Genomics, 11(1). doi: 10.1186/s12920-018-0425-z
[3] Mugnaini, E. N., & Ghosh, N. (2016). Lymphoma. Primary Care: Clinics in Office Practice, 43(4), 661–675. doi: 10.1016/j.pop.2016.07.012
[4] Horn, H., Kohler, C., Witzig, R., Kreuz, M., Leich, E., Klapper, W., … Ott, G. (2018). Gene expression profiling reveals a close relationship between follicular lymphoma grade 3A and 3B, but distinct profiles of follicular lymphoma grade 1 and 2. Haematologica, 103(7), 1182–1190. doi: 10.3324/haematol.2017.181024
[5] Gravelle, P., Burroni, B., Péricart, S., Rossi, C., Bezombes, C., Tosolini, M., … Laurent, C. (2017). Mechanisms of PD-1/PD-L1 expression and prognostic relevance in non-Hodgkin lymphoma: a summary of immunohistochemical studies. Oncotarget, 8(27). doi: 10.18632/oncotarget.16680

**Comment by jyang259** [comment]
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Sihaoyu Gao | Statistics | Exploratory Data Analysis, Modeling, R |  @Sihaoyu1220|
| Kristina Wright | Bioinformatics  |  Computational Biology | @kristinawright |
| Jenny Yang | Bioinformatics  | Machine Learning, Personalized Medicine | @jyang259 |
| Xue Yin | Forest Pathology  | Molecular ecology |@xueyin94|

<b>Team name: </b> Fantastic Yeasts

<b>Project: </b> Many things university students love - beer, wine, bread, pharmaceuticals - are produced from yeasts (Saccharomyces cerevisiae). We propose to analyze a yeast gene expression dataset, which contains 6072 genes from 92 samples. By analyzing this dataset, we can advance our understanding of how variations in conditions (starved, stressed, heat exposure, etc.) can affect the gene expression of yeast cells.  Differentially expressed genes can then be enriched to identify key biological pathways associated with its experimental condition. Additionally, genes that are involved in important mechanisms, can potentially be used as biomarkers for future research in food science, drug discovery, and understanding diseases.   

<b> Dataset used: </b> https://www.kaggle.com/costalaether/yeast-transcriptomics#SC_expression.csv

**Comment by LilyYuanXia** [comment]
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Hassan Ali | Interdisciplinary Oncology |  Subtype specific targeting, bioinformatics | @hasan-ali|
| Lily Xia | Statistics  | Modelling, Machine Learning | @LilyYuanXia |
| Jingyiran Li | Statistics  |Causal Inference  | @lijingyiran|
| Simran Samra | Experimental Medicine  |  Biochemistry, Atopic disorders|@SSAMRA14|

**Team name:** Genome Surfers

**One paragraph on the basic idea of the project:**

Pancreatic adenocarcinoma (PAAD) is the most prevalent form of pancreatic cancer. With a 5 year survival of less than 10%, it is highly aggressive as 80-90% of patients present with surgically unresectable disease [1-2]. We hypothesize that certain genes are more heavily expressed in patients with a longer survival time while others seem to associate with shorter survival. Identifying gene targets would enable us to identify ideal chemotherapeutic drug candidates and create a tailored therapy regimen. This hypothesis will be investigated using the TCGA-PAAD dataset from The Cancer Genome Atlas (TCGA). The dataset contains 44,084 gene expression from 177 patients suffering from PAAD. The libraries were sequenced on the Illumina HiSeq 2000 [3]. Gene expression levels are measured using RPKM (Reads Per Kilobase of transcript per Million mapped reads) in log10 scale. This dataset additionally contains subject demographics, including, gender, age, race, vital status, year of diagnosis, birth year, death year, and other survival-related information. First, clustering algorithms will be applied to cluster all subjects based on gene expression to identify possible structures that might be present in the data. Then, relevant survival analysis techniques will be used to determine whether differences in gene expression levels and survival times are statistically significant. Finally, training subjects will be classified into a vital status (alive or dead) using appropriate classification techniques, and the classification/prediction model that we get from the training set will be tested on the testing set and validated by k-fold cross-validation. The performance of the classification will be assessed using AUC value for the ROC curve, sensitivity, accuracy, and specificity. 

[1] Schneider G, Siveke JT, Eckel F, Schmid RM. Pancreatic cancer: basic and clinical aspects. Gastroenterology 128(6):1606-1625, 2005.

[2] Conroy  T, Bachet  JB, Ayav  A, Huguet  F, Lambert  A, Caramella  C. Current standards and new innovative approaches for treatment of pancreatic cancer.Eur J Cancer 2016;57:10–22.

[3] Cancer Genome Atlas Research Network. Electronic address: andrew_aguirre@dfci.harvard.edu; Cancer Genome Atlas Research Network. Integrated Genomic Characterization of Pancreatic Ductal Adenocarcinoma. Cancer Cell. 2017;32(2):185–203.e13. doi:10.1016/j.ccell.2017.07.007

**Comment by padster** [comment]
| Name | Department/Program | Expertise/Interests | GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Patrick Coleman | Neuroscience | Computational Neuroscience | @padster |
| Abbi Chapman | Biochemistry and Molecular Biology | Everything honey bees, proteomics | @abbichapman |
| Yue Huang (Will) | Bioinformatics Master program | Protein structure analysis in silico | @willhahah |
| Marco Tello | Bioinformatics | Systems Biology | @mtello22 |


**Team name:** 
Go with the Flow

**One paragraph on the basic idea of the project:** 
[Flow Cytometry](https://link.springer.com/protocol/10.1007%2F978-1-61737-950-5_1) allows us to perform high-throughput analysis at the single cell level, measuring fluorescence intensities of multiple colours at the same time. When used in combination with [fluorescent antibodies](https://courses.lumenlearning.com/microbiology/chapter/fluorescent-antibody-techniques/) for proteins of interest, it is possible to quantify the distribution of levels of the proteins in large cell populations. Our data set contains flow cytometry readings generated from human embryonic kidney cells ([HEK293](https://www.sciencedirect.com/science/article/pii/S1056871905000110)) that have been transfected with the wild type and multiple variants of the gene [PTEN](https://www.sciencedirect.com/topics/neuroscience/pten-gene), whose mutations have been associated with both cancer and Autism Spectrum Disorders (ASD). By applying the fluorescent antibodies of the reporter proteins, we will be able to examine how the mutations affect the expression of these proteins at the single cell level across thousands of cells. Depending on the progress of the project, we may be able to examine known pathways involving these proteins, and attempt to predict where exactly in the pathway each variant interferes.

**Comment by HEngelbrecht** [comment]
| Name | Department/Program | Expertise/Interests | GitHub ID | 
| Hannah-Ruth Engelbrecht | Genome Science and Technology | Neuropsychiatric genetics, NGS (WGS+WES), Epigenetics | @HEngelbrecht |
| Jimmy Liu | Bioinformatics | Bacterial Genomics, Phylogenetics | @jimmyliu1326 |
| Qinkai Wu | Bioinformatics | RNA-seq, Machine Learning  | @wu-2018 |
| Henry Tung | Experimental Medicine | RNA-seq (single, bulk) | @14lwt1 |

*Team name:*  Brainiacs

Neurological and psychiatric disorders are a growing public health concern, with minimal definitive intervention strategies available in most cases (1-3). In many cases, the molecular mechanisms of such disorders remain poorly understood, and this presents a challenge in developing effective treatment strategies. Examining specific molecular properties of brain cell types can serve as a preliminary step in understanding pathogenesis. In particular, gene expression is the interface between the genome, epigenetic conditions in the cell, and the phenotype. However, analyzing gene expression profiles is further complicated by which the brain is a complex organ with multiple cell types supporting a structure that is divided into multiple functional regions, each of which is composed of highly heterogeneous subpopulations (4). Consequently, characterisation of bulk brain tissues cannot effectively capture the differences between subpopulations, and is limited to observing signals averaged across them. With the advent of single cell sequencing, there is an opportunity to investigate the expression profiles of these candidate genes across the brain at unprecedented resolution. Specifically, spatial single cell transcriptomics facilitate the investigation of cell-level processes across multiple regions of the brain at a single point in time (5, 6).  Mice are a useful model organism for assessing differential expression across the brain (7), and thus this project will be studying cell type differences in the context of mice. This project aims to investigate the differential expression of genes putatively associated with neurological and psychiatric conditions in a healthy mouse brain, across brain regions and cell types, using the 10x single-cell spatial transcriptomic dataset [https://support.10xgenomics.com/spatial-gene-expression/datasets]. We will subsequently compare the expression profiles under healthy conditions to that of diseased brains using data available from the Allen Brain Atlas and the Gene Expression Omnibus (GEO) to determine whether any clear signals of disease are evident in the spatial organisation of gene expression across cell types and brain regions under disease conditions. The genes we intend to investigate are PAX6, BDNF, CACNA1C, SCN2A, and CHD8. 

World Health Organization. Neurological disorders: public health challenges. (World Health Organization, 2006).
Feigin, V. L. et al. Global, regional, and national burden of neurological disorders, 1990–2016: a systematic analysis for the Global Burden of Disease Study 2016. Lancet Neurol. 18, 459–480 (2019).
Pringsheim, T., Fiest, K. & Jette, N. The international incidence and prevalence of neurologic conditions: How common are they? Neurology 83, 1661–1664 (2014).
Davidson, R. J. & Hugdahl, K. Brain asymmetry. (Mit Press, 1996).
Burgess, D. J. Spatial transcriptomics coming of age. Nat. Rev. Genet. 20, 317–317 (2019).
Maynard, K. R., Jaffe, A. E. & Martinowich, K. Spatial transcriptomics: putting genome-wide expression on the map. Neuropsychopharmacology 45, 232–233 (2020).
Chesselet, M.-F. & Carmichael, S. T. Animal models of neurological disorders. Neurotherapeutics 9, 241–4 (2012).

**Comment by mksm1228** [comment]
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Ali Mirza  | Bioinformatics | Neurology, Human Microbiome, Exposome   |  @aimirza |
| Kimberly Vreugdenhil | Genome Science and Technology  |  Bacterial Genetics, Synthetic Ecology | @kvreug |
| Rodrigo Vallejos  |  Genome Science and Technology |  Epigenetics, Immunology | @awakenedhaki |
| Martin Keung | Neuroscience  | Spinal cord injury, Neurogenic bladder  | @mksm1228 | 

**Team Name:** The Gut's brain feeling

Schizophrenia is a chronic mental illness disorder characterized by an array of symptoms including delusions, hallucinations, and impaired cognitive ability. Effective pharmacologic treatments exist, but identification of the pathology and etiology has been quite difficult as multiple factors ranging from socioeconomic status to genetic makeup can play a role in the development of the illness. Recent research has shown that the gut microbiome can modulate brain function and behaviours through the microbiota-gut-brain axis. For this group project, we will be using the data set authored by Nguyen et al.  to investigate differences in the gut microbiome composition between persons with chronic schizophrenia (> 10 years, n=25) and healthy comparison subjects (n=25). This rich cohort includes a rich variety of covariates, such as medication, treatments, allergies, comorbidities, mental conditions, diet, exercise, other environmental exposures, and more. If there are differences in the schizophrenia microbiome (vs controls), we are interested to know how much of those differences are explained by covariates.

https://qiita.ucsd.edu/study/description/11710

Nguyen, Tanya T. et al. "Differences In Gut Microbiome Composition Between Persons With Chronic Schizophrenia And Healthy Comparison Subjects". Schizophrenia Research, vol 204, 2019, pp. 23-29. Elsevier BV, https://doi.org/10.1016/j.schres.2018.09.014

**Comment by jsicherman** [comment]
| Name | Department/Program | Expertise/Interests | GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Lucía Quesada-Ramírez | GSAT | Plant genomics, polyploidy | @luciaq21 |
| Saelin Bjornson | Bioinformatics | Comparative genomics, phylogenetics, evolution | @SaelinB |
| Vladimir Nikolic | Bioinformatics | Genome assembly, algorithms, cats | @schutzekatze |
| Jordan Sicherman | Bioinformatics | snRNAseq, differential expression analysis, not cats | @jsicherman |

Team name: RNAseekers 🧬📊🤓

Single-cell RNASeq (scRNAseq) offers a powerful method of analyzing cell-type heterogeneity within biological tissues. However, there are a number of difficulties in collecting the single cells, leading to unique challenges in data analysis. One such issue is known as dropout, wherein transcripts that are actually present in the sample go undetected in its sequenced RNA profile. This results in a pile-up of read abundances near 0, some of which are *true zeros* (the cell didn't contain any transcripts) and the rest are *excess zeros* (which arose due to dropout), resulting in expression profiles that are characteristically non-normal. The frequency of dropouts has been previously shown to be protocol-dependent, showing some technical bias. It has also been shown to be expression-level dependent, in which lowly expressed transcripts dropout at higher rates. We aim to further characterize these biases in dropout rates. We will do this using data from experiments that provide paired scRNAseq and bulk tissue RNAseq data: expression levels between these two sets should be highly correlated, so by analyzing differences in gene abundances between the two, we can find interesting genes for further study. Genes with expression levels that do not correlate between the two will be analyzed for over-representation of interesting biological properties, such as gene length, functional assignments and GC-content. We know specifically of 3 such experiments, covering a total of 90 individuals over multiple sequencing platforms.

**Comment by dy-lin** [comment]
| Name | Department/Program | Expertise/Interests |GitHub ID | 
| ------------- | ------------- | ------------- | ------------- |
| Diana Lin | Bioinformatics | Genome/Transcriptome Assembly, Bioinformatics Pipeline Development, Mammalian Physiology, Datamining | [@dy-lin](https://github.com/dy-lin) |
| Almas Khan | Bioinformatics  | Epigenetics, mammalian biology, microbiology  |[@almas2019](https://github.com/almas2019) |
| Denitsa Vasileva | Bioinformatics  | Gene Set Enrichment Analysis, Epigenetics, PPI Networks  |[@Deni678](https://github.com/Deni678)|
| Nairuz Elazzabi | Medical Genetics | Neurodevelopmental Genetics, Epigenetics, Transcriptome Profiling | [@Nayrouz109](https://github.com/Nayrouz109)|

### The Splice Girls

Leukemia is a type of cancer that originates and affects the bone marrow. Leukemia accounts for roughly 3.5% of all new cancer diagnoses. Two of the most common types of leukemia are T-cell Acute Lymphoblastic Leukemia (T-ALL)  and Acute Myeloid Leukemia (AML). 

We propose to look at an expression profile dataset containing these two types of leukemia found on GEO. We aim to look for differentially expressed genes in different subtypes of each leukemia - including alpha beta, gamma delta, TR beta rearrangement T-ALL and M0 AML- as well as across the different the two leukemia types. These results would help profile patients with heterogeneous leukemias. To do this we will utilize the [GSE131184](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE131184) dataset. This dataset contains RNA expression microarray data from the bone marrow of 125 patients- with either T-ALL or AML. 

We also plan to look at ~480 single cell RNA-seq (scRNA-seq) samples taken from Hematopoietic Stem Cells (HSCs) in the bone marrow of two healthy deceased donors. This dataset is taken from the same lab as our leukemia samples and is found at [GSE143567](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE143567).
