### ISSUE TITLE
Interaction Effect Graphs

### ISSUE THREAD

**Issue by dy-lin** [STAT540-UBC/Discussion#352]
@kdkorthauer, can you clarify how to conclude whether or not there is an 'interaction' effect from these two slides from lecture 07? In particular, `1448243_at` from Example 1 doesn't look very parallel/flat?

![ex1-flat](https://user-images.githubusercontent.com/44071582/73880637-a64f1300-4813-11ea-90ec-46c6907d2dea.png)

![ex2-nonparallel](https://user-images.githubusercontent.com/44071582/73880647-a94a0380-4813-11ea-8ee5-80d178863117.png)

**Comment by jsicherman** [comment]
I think the idea is that they have to fulfill 2 criteria to demonstrate interaction:
1. They have to be significantly differentially expressed
2. The direction of DE should be the same

In example 1, I assume it doesn't fulfill the first criterion (since they don't look differentially expressed wrt developmental stage) so we can't actually conclude anything about it.

In example 2, both genes (probes) are differentially expressed, but since their directions of DE are different (downregulated in one, upregulated in the other), the genotype must have some significant interaction with developmental stage.

The other case is when the first criterion (statistically significant DE) is fulfilled, but the direction of change is the same. This would demonstrate at most a weak interaction effect. I suppose we can't conclude there is *no* (significant) interaction effect by using these graphs (unless they were exactly parallel?), just that the effect is weak. Maybe if they went the same direction but the slope of the line in one was many fold higher between genotypes, this would also demonstrate an (additive?) interaction effect, but I'm not sure.

This is my understanding, anyways. I'm happy to be corrected if I'm off track.

**Comment by ppavlidis** [comment]
@dy-lin you are right that the slopes are different, but the intent of this example was that it's "not statistically significantly different". The lines are there to help visualize, but just focus on the individual data points and you'll see that the difference between the developmental stages is small compared to the variance within the groups. Compared to the bottom examples.

@jsicherman, Your point 2 is more correct if you change it to "shouldn't" (I think you meant that based on the next part). But it's not quite right - you could observe a positive (or negative) slope in both genotypes, just larger in one than the other, like you say later. That's still an interaction.

A related point is that it doesn't have to be "flat" to be a "non-interaction". You could have a huge effect of developmental stage, but the same direction and magnitude in both genotypes. There are other scenarios you might be able to think of. In general if the slopes are "significantly different", we call that an interaction.

**Comment by kdkorthauer** [comment]
Thanks for you question, @dy-lin, and thanks for chiming in @jsicherman and @ppavlidis !

Yes, it's important to note that the interaction effect does not have to be flat -- **parallel** lines in this context that both have a significant slope would indicate differential expression by developmental stage, but no interaction with genotype. The fact that the lines are relatively flat in Example 1, demonstrate no significant main effect of developmental stage. Their lack of interaction is seen in that the slopes are not **significantly** different. As @dy-lin points out, the lines in `1448243_at` are not visually perfectly parallel, but if we look at the model fit for that probe, we see that the interaction effect is not significant (meaning that the slope of the two lines is not significantly different):

```
> prDat<-read.table("data/GSE4051_data.tsv",
+                   sep = "\t", header = T, row.names = 1)
> 
> egDat<-prDat %>% 
+   subset(row.names(prDat) %in% c("1448243_at")) %>%
+   tibble::rownames_to_column(var = "gene" )%>% 
+   gather(sidChar, gExp,-gene) %>%
+   inner_join(prDes,by="sidChar")
> 
> summary(lm(gExp ~ gType*devStage, data=egDat))

Call:
lm(formula = gExp ~ gType * devStage, data = egDat)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.7580 -0.2404 -0.0390  0.2316  1.0802 

Coefficients:
                           Estimate Std. Error t value Pr(>|t|)    
(Intercept)                  8.5240     0.2561  33.280 2.15e-12 ***
gTypeNrlKO                  -0.4337     0.3912  -1.108    0.291    
devStage4_weeks             -0.2533     0.3622  -0.699    0.499    
gTypeNrlKO:devStage4_weeks   0.5504     0.5332   1.032    0.324    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.5123 on 11 degrees of freedom
Multiple R-squared:  0.1081,	Adjusted R-squared:  -0.1351 
F-statistic: 0.4446 on 3 and 11 DF,  p-value: 0.726
```

As @ppavlidis points out, visually you can see that the spread of the individual points here is large compared to the magnitude of difference in developmental group.

**Comment by jafarzadeh91** [comment]
Just to put my two cents: 
It is kind of philosophical but you should really stick to your null unless you have evidence not doing so. similar to the "innocent until proven guilty" adage.  remember that in hypothesis testing, we assume the null hypothesis as default and what we speculate is whether we **really** have enough evidence to reject the null or not.  The small amount of evidence  (as in 1448243), given the small number samples, doesn't seem visually appealing enough to me to **reject**  the default which is no interaction.  The question is not whether this lines are non-parallel (of course they are!). the question is whether these lines are non-parallel **enough** (i.e. the low p-value) to allow me to reject the default assumption of being parallel (no interaction).
