### ISSUE TITLE
ermineR method

### ISSUE THREAD

**Issue by naila53** [STAT540-UBC/Discussion#394]
Hi @ppavlidis,

I'm adopting `fgsea` package for gene set enrichment analysis in my workflow just because it's fast and highly popularized as it's linked to the Broad institute's GSEA software. After your lecture I went through seminar 10 that discusses ermineR method developed by your team.
I'm not sure I understand how to interpret the MFP.pvalue. How to select significantly enriched pathways while accounting for Multi Functionality as well?  with fgsea, I just select pathway padj<0.05.

to select for significantly enriched pathways in ermineR I would run:
> enrichmentResult$results%>% arrange(MFPvalue) %>%filter(CorrectedPvalue<0.05, CorrectedMFPvalue>0.05)

is this correct?

**Comment by ppavlidis** [comment]
That's reasonable. The way we describe it in the paper (and in the STAT540 lecture) is that the non-MF-adjusted results aren't invalid, they are just (potentially) generic and thus less helpful. To help focus on terms that are more likely to be specific to your data you can use a filter like you suggest. I know it's a slightly subtle thing, but that's because the way people interpret enrichment results is not well defined.

If your gene ranking does not have an appreciable correlation with the multifunctionality gene ranking, then the effect of MF correction will tend to be low. But correlation doesn't capture the effect perfectly, and "appreciable" does not have to be very high: even correlations as low as 0.1 should be considered worth checking, and just a couple highly MF genes near the top of your ranking can have effects. You can look at that even if you use GSEA. For what it is worth, the ROC method offered in ermineR i similar in concept to the GSEA algorithm (the PR method is too, but with a different weighting for the ranks of the genes in the pathway, in effect).

**Comment by naila53** [comment]
thanks @ppavlidis for the clarification. I obtained similar results when I applied `fgsea` at number of permutations=10000 and ermineR. In comparisons where I didn't have significant enrichments in `fgsea` at padj<0.05, I also didn't get significant pathways at CorrectedPvalue<0.05& CorrectedMFPvalue>0.05  in ermineR. 

I now find ermineR much more user friendly, cleaner and insightful. will definitely switch to it,   wonderful work!
Thanks!
