### ISSUE TITLE
Submission formats

### ISSUE THREAD

**Issue by rmcclosk** [STAT540-UBC/Discussion#45]
I'm a bit confused about the [instructions](http://stat540-ubc.github.io/assignments.html) for handing in assignments. Why do we need to submit both a `.md` file and a `.html` file? It's possible to render both of these types of files directly from the `.Rmd` file, like this:

```
library(rmarkdown)
render('foo.Rmd', md_document(variant='markdown_github'))
render('foo.Rmd', html_document())
```

It seems kind of redundant to have both, especially when markdown displays nicely within github, but html requires more effort to get a useful preview.

**Comment by jennybc** [comment]
FWIW, the html is very useful to you locally, as you work on the assignment. If you only render to md, your local sense of how the assignment is going and how it will look is … very poor.

And as you point out the Markdown is the most useful on GitHub.

This is how we get to a place where we recommend keep `.Rmd` --> `.md` --> `.html` in the repo. The submission of all 3 files is much harder than any one of them. 3 clicks when making a commit.

But I agree the html does little for us on GitHub. However, since it's useful locally, you'll probably want to be committing it.

**Comment by rmcclosk** [comment]
Ah okay, I see. Thanks!

**Comment by jennybc** [comment]
I just read your code. You do realize it's much easier to get both the markdown and HTML, yes? I explain it here:

http://stat545-ubc.github.io/block007_first-use-rmarkdown.html

Specifically, you need to beef up your YAML and you'll get it all in one `render()`, whether it's via mouse click or explicit call. Heck, you could save to PDF or Word while you're at it...
