### ISSUE TITLE
Difference in non-interaction terms when lm() for A * B and A + B 

### ISSUE THREAD

**Issue by mas29** [STAT540-UBC/Discussion#49]
Why are results different for non-interaction terms (ex. estimate, SE, t and p-values for A and B separately) when using "val ~ A * B" and "val ~ A + B"?

**Comment by kmnip** [comment]
I don't think the coefficients have the same meaning in the 2 models (ie. with vs without interaction). 

Regression equation without the interaction term:
`val = a_0 + a_1*A + a_2*B`

`a_1` tells you the unique effect of A on `val`.
`a_2` tells you the unique effect of B on `val`.

Regression equation with the interaction term:
`val = a_0 + a_1*A + a_2*B + a_3*A*B`

Here, you assume there is interaction between A and B.
`a_1` tells you the unique effect of A on `val` **only when B = 0**.
`a_2` tells you the unique effect of B on `val` **only when A = 0**.
So, these coefficients have quite different meaning now.

Besides, you would only get the same result for non-interaction terms only if the results are zero for all interaction terms. I guess `lm()` would never do that and return some small numbers instead because you do expect interaction (given `*` instead of `+`).

Ka Ming

**Comment by mas29** [comment]
Ah, I see. Thanks a lot, Ka Ming!

**Comment by gcohenfr** [comment]
Great quantitative explanation Ka Ming!! If you want to think of this graphically, remember that a model without interaction assumes parallel lines or patterns, while a model with interaction will allow lines to cross. Thus, they won't be the same, they are measuring different effects.
