### ISSUE TITLE
Making the seminar's exercises available before the seminar takes place

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#5]
Is it possible to have the seminar exercises available before Wednesday ? Perhaps Monday ?

It would be great if I could attempt the exercises myself beforehand and then if I have questions, I would ask the TAs during the seminar.

Thanks!

**Comment by kmnip** [comment]
I agree with this, considering that we only have ~1 hour of tutorial time now.
I find myself spending most of my time at the lab reading/understanding the seminar, which is probably not a good use of the TAs' time.

Thanks!
Ka Ming

**Comment by aliceZhu** [comment]
It's great that you guys are eager to try them beforehand! We will try to make them available as soon as possible, probably starting from the next seminar (week 4). For seminar 3, we might have to spend most of the seminar time configuring the connection to github (since it's important to get this configuration done asap so you could submit your seminar homework/exercise to your remote repository).

**Comment by IssamLaradji** [comment]
Thanks!
