### ISSUE TITLE
Issue with estimating the FDR

### ISSUE THREAD

**Issue by IssamLaradji** [STAT540-UBC/Discussion#62]
The formula for estimating the FDR is given as,
![iebjehja](https://cloud.githubusercontent.com/assets/3382128/6432403/3f09359a-c005-11e4-92a8-5d3458823f0f.png)

The values for `t`, `m`, and `#{p_i < t}` can all be computed. 

However, how would we estimate 
![dcaiidej](https://cloud.githubusercontent.com/assets/3382128/6432406/6ac5c004-c005-11e4-848a-99ac507efd06.png) ?

In other words how do we estimate the proportion of the true null genes? I found that the `convest` method [1] can be used to estimate it. But the tool is beyond the scope of the course. 

The slides don't seem to mention a way of estimating it. Do we just assume that the proportion of the true null genes is `m - # hits` where `m` is the number of probes, and `# hits` is the number of hits.

Thanks.

[1] http://www.cse.unsw.edu.au/~mike/myrlibrary.old/limma/html/convest.html

**Comment by ppavlidis** [comment]
Hi,

For Benjamini-Hochberg, the estimate is that pi0 = 1.0; that is, there is no differential 
expression (or whatever). The way I like to describe it is if there is no actual signal 
(no differential expression; the "complete null hypothesis"), then the expected number of 
null rejections is simply

#of tests * p-value threshold

Example:

test 10000 genes at a nominal pvalue of 0.01, you will get 10000*0.01 = 100 null 
rejections under the complete null. That comes just from the definition of pvalues.

Thus in your experiment if you reject 200 genes at p<0.01 (meaning: 200 genes had a pvalue 
<0.01), your estimated FDR is 0.5 (because you would have rejected 100 under the complete 
null). Obviously if you want the FDR to be 0.05 you have to change the p-value threshold; 
B-H helps you find the p-value threshold given the FDR you want.

(Benjamini-Hochberg is slightly more complex than this in that the "optimal" p-value 
threshold (in terms of maximizing the # of rejections) to maintain an FDR of 0.5 might be 
different than 0.01, but that's the essential idea)

For Storey's q-value, the estimate of pi0 is made by the software, using the properties of 
the observed p-value distribution. You'd have to read their paper to see how they do this 
(there are at least two ways they implemented), but basically they're trying to estimate 
how many of the observed p-values come from a uniform distribution (the complete null) 
from the shape of the observed distribution.

I hope that helps.

tagging
@gcohenfr
@wdurnoUBC
@aliceZhu

P

**Comment by IssamLaradji** [comment]
Thanks a lot! this really helps. However, as you mentioned, 
the expected number of null rejections is simply "#of tests * p-value threshold"

Is this p-value threshold the unadjusted p-value or the FDR adjusted p-value ? or does that not matter since they are equivalent ?

Thanks.

**Comment by ppavlidis** [comment]
Uh-oh, your question suggests you might not understand what's happening when we "control 
the FDR".

FDR-controlling procedures do not take in p-values and (given the FDR you want to shoot 
for) output p-values. The actual output to think about is the "hit list" of genes ("there 
are 201 genes selected with an estimated FDR of 10%"). The q-values are just a side-effect 
-- you don't use them to say something about a specific gene (you don't say "this gene has 
FDR 0.04", where 0.04 is the q-value -- absolutely wrong).

My example may have confused you because it starts from a p-value threshold and then tells 
you what the FDR is. If you understand how I got that, at least, now think about how you 
might proceed if I told you what FDR I wanted, instead of telling you the p-value 
threshold I wanted to use.

(I'm not giving a direct answer to your question, yet)

**Comment by gcohenfr** [comment]
The full lecture on Mult Testing explains how pi0 is estimated. You can also read their paper directly for more details.

**Comment by IssamLaradji** [comment]
Thank you for the elaborate answers. After going through the related lectures more thoroughly, I got a clear idea what FDR adjusted p-values mean. Thank you.
