### ISSUE TITLE
HW2 peer review assignment

### ISSUE THREAD

**Issue by gcohenfr** [STAT540-UBC/Discussion#88]
Hi @jennybc , students finished hw2. They've all opened an issue titled "Mark hw02 of zz_lastname-firstname_STAT540_2015", last word being their repo name.

Will you be able to read these issues, assign reviewers, open Issues with assignments? We are at the last week of classes, so please, let me know if you will be able to do this. Otherwise, I'll find another way or I may replace this peer evaluation with the poster one. Thanks, G

**Comment by jennybc** [comment]
Did you mean to open this here in Disucssion or over in the Instructors repo?

Regardless, yes I can do it. I recall there were a few *post hoc* modifications last time, perhaps due to an auditor being in the mix? Can you send me an email with the name(s) of the people to exclude before I make the review assignments and open the issues?

**Comment by jennybc** [comment]
Oh wait, now I see our discussion in the other repo about proactively searching the issues and only doing peer review within that group. Let me try to do that ….

**Comment by jennybc** [comment]
Issues assigned!
