### ISSUE TITLE
Answer to Question #1

### ISSUE THREAD

**Issue by samhinshaw** [STAT540-UBC/Discussion#93]
In today's lecture, we compared two methods for solving Question 1:  
- Using the binomial distribution to predict the number of outcomes with 7 heads  
- Running a simulation of coin flips using a uniform distribution `runif`, and seeing how many outcomes we got with 7 heads  

We then tested each of these methods against a simulation (`obsFreq`) with `rbinom` & calculated `pSad`.  As it turns out, the `runif` simulation was slightly more accurate than using the binomial distribution
(`pSad = 0.0027` vs `pSad = 0.0009`)

I know this wasn't the point of the the lecture, but I'm just curious...
Isn't this really just testing R's RNG performance, and saying that `rbinom` more closely matches `runif` than it does the true theoretical binomial distribution?

**Comment by marjanfarahbod** [comment]
Good question and food for thought indeed!

##### First
Please notice that the example in the lecture was just _one trial_ of the experiment. This means that if you run the code again, you will get different numbers from both `runif` and `rbinom` methods.   

##### Second
It is also worth to notice that, there is actually a very little chance (and as the number of trials B gets bigger, it gets closer to zero) that we observe the _exact_ value calculated by math from either of the `runif` or `rbinom` methods. The errors get smaller as we increase B, but the chance to see the exact value calculated by math also gets smaller. 

##### Third 
`runif` is just a *uniform variable generator*. Here we used it to simulate our coin flip trials (each trial is 10 coin flips). Each coin flip has a chance to be head or tail, with p = 0.5. Then we use these coin flip trials to calculate our binomial variable for the test: the number of times we have 7 heads in B = 10000 trials. `runif` itself, is a good uniform variable generator *if* it is not biased, meaning that if it is not showing more heads or showing more tails, in the over al experiment. Please let me know if you wish to see how this could be tested. In the lecture example, `runif` was used to simulate a more realistic experiment by generating coin flip results and then calculating the binomial variable from them. 

 `rbinom` on the other hand, is a binomial generator with "random deviates" (exactly as mentioned in R help), meaning that it is trying to perform like a binomial trial, with some expected error from the value calculated by math value, as there always is. 

So in the end, both of the methods mentioned in the lecture for simulating the experiment, should be performing well in estimating the actual mathematical value. Knowing that there is a little chance that we ever get the exact mathematical value, we can guess that a good estimator would sometimes have a bigger value and sometimes have a smaller value, but either case, the value should be close to the mathematical value. 

#### Your answer

After all these explanations, I believe your answer is no. The estimators are not closer to each other than they are closer to mathematical value. Here is why (and not a very concrete proof): if `rbinom` and `runif` tend to be closer to each other (and I am not talking about a single example, I am talking about if we run each of them many times) than they are closer to the mathematical value we calculated (let's call it the **true value**), they must be both either bigger or smaller than the true value (cause if the true value is in between them, it is closer to both of them than they are to each other, right?). Now, considering that `rbinom` and `runif` are independent from each other (even if you run their code right after each other, they use different random seeds), that means, to be *always* on one side of the true value, they both must be always bigger than the true value or smaller than the true value, that means they are **biased** and therefore, they are not good estimators. I guess this is highly unlikely, since I assume that R is doing fine in random number generating. Variances are fine, but **bias** in an estimate could be a big issue. 

### We can try some code:

The performance of `runif` and `rbinom` could be studied using the code below, which is just a loop of the code in the lecture and generates 10000 estimates from each of the two methods. My hypothesis is that: in various trials of the same code in the lecture, I will get values from `runif` and `rbinom`, some of which are bigger and some smaller than the true value. We can check the distribution too. 

```R
 for(i in  1:10000){
obsFreq[i] = sum(rbinom(n = B, size = n, prob = p) == x)
}

for(i in 1:10000){
coinFlips= runif(n*B) > 0.5 
coinFlips <- matrix(coinFlips, nrow = B)
y <- rowSums(coinFlips)
myGuess[i] <- sum(y ==7)
}

> mean(obsFreq)
[1] 1171.948
> mean(myGuess)
[1] 1171.866

```

Now let's see the plots for estimated values for each of them: 

The distribution plot for **myGuess** (from `runif`)
![image](https://cloud.githubusercontent.com/assets/14799345/12226448/2976de84-b7d1-11e5-8b8a-327fd85197a4.png)

The distribution plot for **obsFreq** (from `rbinom`)
![image](https://cloud.githubusercontent.com/assets/14799345/12226503/dc29819e-b7d1-11e5-8f6b-298dd4de62ad.png)
